const horarios = {
    "primero": {
        "1-1": [
            ["7:00 AM - 7:45 AM", "ARGUETA PORTILLO, JOSÉ MARIO ANTONIO CIENCIAS NATURALES", "ARGUETA PORTILLO, JOSÉ MARIO ANTONIOCIENCIAS NATURALES", "ARÉVALO ROSALES, JUAN ALBERTO IDIOMA EXTRANJERO", "ARÉVALO ROSALES, JUAN ALBERTO IDIOMA EXTRANJERO", ""],
            ["7:45 AM - 8:30 AM", "ARGUETA PORTILLO, JOSÉ MARIO ANTONIOCIENCIAS NATURALES", "ARGUETA PORTILLO, JOSÉ MARIO ANTONIO CIENCIAS NATURALES", "ARÉVALO ROSALES, JUAN ALBERTO IDIOMA EXTRANJERO", "ARÉVALO ROSALES, JUAN ALBERTO IDIOMA EXTRANJERO", ""],
            ["8:30 AM - 8:45 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["8:45 AM - 9:30 AM", "", "", "ARGUETA PORTILLO, JOSÉ MARIO ANTONIO CIENCIAS NATURALES", "AQUINO SÁNCHEZ, LORENA LISSETTE MOD 1.7 AC", ""],
            ["9:30 AM - 10:15 AM", "SARAVIA  DE YUDICE,EVELYN YANETHLENGUAJE Y LITERATURA", "ARÉVALO ROSALES, JUAN ALBERTO IDIOMA EXTRANJERO", "ARGUETA PORTILLO, JOSÉ MARIO ANTONIO CIENCIAS NATURALES", "", ""],
            ["10:15 AM - 10:30 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["10:30 AM - 11:15 PM", "SARAVIA  DE YUDICE,EVELYN YANETH LENGUAJE Y LITERATURA", "PÉREZ MARTÍNEZ, RENE ALFREDO EDUCACIÓN FÍSICA", "SARAVIA  DE YUDICE,EVELYN YANETH LENGUAJE Y LITERATURA", "GUZMAN  DE NAVIDAD,FANNY PATRICIA MOD 1.6 AC", ""],
            ["11:15 PM - 12:00 PM", "SARAVIA  DE YUDICE,EVELYN YANETH LENGUAJE Y LITERATURA", "PÉREZ MARTÍNEZ, RENEALFREDO EDUCACIÓN FÍSICA", "SARAVIA  DE YUDICE,EVELYN YANETH LENGUAJE Y LITERATURA", "GUZMAN  DE NAVIDAD,FANNY PATRICIA MOD 1.6 AC", ""],
            ["12:00 PM - 1:00 PM",  "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["1:00 PM - 1:45 PM", "AQUINO SÁNCHEZ, LORENA LISSETTE MOD 1.7 AC", "PREZA DÍAZ, ROBERTO CARLOS MATEMÁTICA", "PREZA DÍAZ, ROBERTO CARLOS MATEMÁTICA", "SOTO RIVERA, EDWIN ALEXANDER ESTUDIOS SOCIALES Y CÍVICA", "MELARA ESCAMILLA, RICARDO ERNESTO INFORMÁTICA"],
            ["1:45 PM - 2:30 PM", "AQUINO SÁNCHEZ, LORENA LISSETTE MOD 1.7 AC", "PREZA DÍAZ, ROBERTO CARLOS MATEMÁTICA", "PREZA DÍAZ, ROBERTO CARLOS MATEMÁTICA", "SOTO RIVERA, EDWIN ALEXANDER ESTUDIOS SOCIALES Y CÍVICA", "MELARA ESCAMILLA, RICARDO ERNESTO INFORMÁTICA"],
            ["2:30 PM - 2:45 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["2:45 PM - 3:30 PM", "PREZA DÍAZ, ROBERTO CARLOS MATEMÁTICA", "HENRÍQUEZ VÁSQUEZ,MARVIN ALFONSO MÓDULO", "HENRÍQUEZ VÁSQUEZ,MARVIN ALFONSO MÓDULO", "SOTO RIVERA, EDWIN ALEXANDER ESTUDIOS SOCIALES Y CÍVICA", ""],
            ["3:30 PM - 4:15 PM", "PREZA DÍAZ, ROBERTO CARLOS MATEMÁTICA", "HENRÍQUEZ VÁSQUEZ,MARVIN ALFONSO MÓDULO", "HENRÍQUEZ VÁSQUEZ,MARVIN ALFONSO MÓDULO", "HENRÍQUEZ VÁSQUEZ,MARVIN ALFONSO MÓDULO", ""],
            ["4:15 PM - 4:30 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["4:30 PM - 5:15 PM", "HENRÍQUEZ VÁSQUEZ,MARVIN ALFONSO MÓDULO", "HENRÍQUEZ VÁSQUEZ,MARVIN ALFONSO MÓDULO", "HENRÍQUEZ VÁSQUEZ,MARVIN ALFONSO MÓDULO", "HENRÍQUEZ VÁSQUEZ,MARVIN ALFONSO MÓDULO", "SOTO RIVERA, EDWIN ALEXANDER ESTUDIOS SOCIALES Y CÍVICA"],
            ["5:15 PM - 6:00 PM", "HENRÍQUEZ VÁSQUEZ,MARVIN ALFONSO MÓDULO", "HENRÍQUEZ VÁSQUEZ,MARVIN ALFONSO MÓDULO", "HENRÍQUEZ VÁSQUEZ,MARVIN ALFONSO MÓDULO", "HENRÍQUEZ VÁSQUEZ,MARVIN ALFONSO MÓDULO", "SOTO RIVERA, EDWIN ALEXANDER ESTUDIOS SOCIALES Y CÍVICA"],
        ],
        "1-2": [
           ["7:00 AM - 7:45 AM", "", "SARAVIA  DE YUDICE,EVELYN YANETH LENGUAJE Y LITERATURA", "SARAVIA  DE YUDICE,EVELYN YANETH LENGUAJE Y LITERATURA", "ARGUETA PORTILLO, JOSÉ MARIO ANTONIO CIENCIAS NATURALES", "SOLANO RIVERA, VICTORIA ELVIRA IDIOMA EXTRANJERO"],
            ["7:45 AM - 8:30 AM", "", "SARAVIA  DE YUDICE,EVELYN YANETH LENGUAJE Y LITERATURA","SARAVIA  DE YUDICE,EVELYN YANETH LENGUAJE Y LITERATURA", "ARGUETA PORTILLO, JOSÉ MARIO ANTONIO CIENCIAS NATURALES", "SOLANO RIVERA, VICTORIA ELVIRA IDIOMA EXTRANJERO"],
            ["8:30 AM - 8:45 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["8:45 AM - 9:30 AM", "", "ARGUETA PORTILLO, JOSÉ MARIO ANTONIO CIENCIAS NATURALES", "", "GUZMAN  DE NAVIDAD,FANNY PATRICIA MOD 1.6 AC", "SARAVIA  DE YUDICE,EVELYN YANETH LENGUAJE Y LITERATURA"],
            ["9:30 AM - 10:15 AM", "","ARGUETA PORTILLO, JOSÉ MARIO ANTONIO CIENCIAS NATURALES", "SOLANO RIVERA, VICTORIA ELVIRA IDIOMA EXTRANJERO", "GUZMAN  DE NAVIDAD,FANNY PATRICIA MOD 1.6 AC", "AQUINO SÁNCHEZ, LORENA LISSETTE MOD 1.7 AC"],
            ["10:15 AM - 10:30 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["10:30 AM - 11:15 PM", "","DÍAZ CALLEJAS, DAVIDMAURICIO INFORMÁTICA", "SOLANO RIVERA, VICTORIA ELVIRA IDIOMA EXTRANJERO", "PÉREZ MARTÍNEZ, RENE ALFREDO EDUCACIÓN FÍSICA", "ARGUETA PORTILLO, JOSÉ MARIO ANTONIO CIENCIAS NATURALES"],
            ["11:15 PM - 12:00 PM", "", "DÍAZ CALLEJAS, DAVIDMAURICIO INFORMÁTICA", "SOLANO RIVERA, VICTORIA ELVIRA IDIOMA EXTRANJERO", "PÉREZ MARTÍNEZ, RENE ALFREDO EDUCACIÓN FÍSICA", "ARGUETA PORTILLO, JOSÉ MARIO ANTONIO CIENCIAS NATURALES"],
            ["12:00 PM - 1:00 PM",  "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["1:00 PM - 1:45 PM", "HENRÍQUEZ VÁSQUEZ,MARVIN ALFONSO MÓDULO", "AQUINO SÁNCHEZ, LORENA LISSETTE MOD 1.7 AC", "HENRÍQUEZ VÁSQUEZ,MARVIN ALFONSO MÓDULO", "HENRÍQUEZ VÁSQUEZ, MARVIN ALFONSO MÓDULO", "HENRÍQUEZ VÁSQUEZ,MARVIN ALFONSO MÓDULO"],
            ["1:45 PM - 2:30 PM", "HENRÍQUEZ VÁSQUEZ,MARVIN ALFONSO MÓDULO", "AQUINO SÁNCHEZ, LORENA LISSETTE MOD 1.7 AC", "HENRÍQUEZ VÁSQUEZ,MARVIN ALFONSO MÓDULO", "HENRÍQUEZ VÁSQUEZ, MARVIN ALFONSO MÓDULO", "HENRÍQUEZ VÁSQUEZ,MARVIN ALFONSO MÓDULO"],
            ["2:30 PM - 2:45 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["2:45 PM - 3:30 PM", "HENRÍQUEZ VÁSQUEZ,MARVIN ALFONSO MÓDULO", "", "PREZA DÍAZ, ROBERTO CARLOS MATEMÁTICA", "HENRÍQUEZ VÁSQUEZ, MARVIN ALFONSO MÓDULO", "HENRÍQUEZ VÁSQUEZ,MARVIN ALFONSO MÓDULO"],
            ["3:30 PM - 4:15 PM", "HENRÍQUEZ VÁSQUEZ,MARVIN ALFONSO MÓDULO", "SOTO RIVERA, EDWIN ALEXANDER ESTUDIOS SOCIALES Y CÍVICA", "PREZA DÍAZ, ROBERTO CARLOS MATEMÁTICA", "", "HENRÍQUEZ VÁSQUEZ,MARVIN ALFONSO MÓDULO"],
            ["4:15 PM - 4:30 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["4:30 PM - 5:15 PM", "PREZA DÍAZ, ROBERTO CARLOS MATEMÁTICA", "PREZA DÍAZ, ROBERTO CARLOS MATEMÁTICA", "SOTO RIVERA, EDWIN ALEXANDER ESTUDIOS SOCIALES Y CÍVICA", "SOTO RIVERA, EDWIN ALEXANDER ESTUDIOS SOCIALES Y CÍVICA", ""],
            ["5:15 PM - 6:00 PM", "PREZA DÍAZ, ROBERTO CARLOS MATEMÁTICA", "PREZA DÍAZ, ROBERTO CARLOS MATEMÁTICA", "SOTO RIVERA, EDWIN ALEXANDER ESTUDIOS SOCIALES Y CÍVICA", "SOTO RIVERA, EDWIN ALEXANDER ESTUDIOS SOCIALES Y CÍVICA", ""],
        ],
        
    },
    "segundo": {
        "2-1": [
             ["7:00 AM - 7:45 AM", "SARAVIA  DE YUDICE,EVELYN YANETH LENGUAJE Y LITERATURA", "MARTÍNEZ DE ALVARENGA,CLARINA ANGÉLICA ORIENTACIÓN PARA LA VIDA", "GARCÍA NAVARRO, CARLOS HUMBERTO CIENCIAS NATURALES", "HERRERA CACERES, CORA LISSETTE MÓDULO", "GARCÍA NAVARRO, CARLOS HUMBERTO CIENCIAS NATURALES"],
            ["7:45 AM - 8:30 AM", "SARAVIA  DE YUDICE,EVELYN YANETH LENGUAJE Y LITERATURA", "MARTÍNEZ DE ALVARENGA,CLARINA ANGÉLICA ORIENTACIÓN PARA LA VIDA", "GARCÍA NAVARRO, CARLOS HUMBERTO CIENCIAS NATURALES", "HERRERA CACERES, CORA LISSETTE MÓDULO", "GARCÍA NAVARRO, CARLOS HUMBERTO CIENCIAS NATURALES"],
            ["8:30 AM - 8:45 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["8:45 AM - 9:30 AM", "HERRERA CACERES, CORA LISSETTE MÓDULO", "GARCÍA NAVARRO, CARLOS HUMBERTO CIENCIAS NATURALES", "SARAVIA  DE YUDICE,EVELYN YANETH LENGUAJE Y LITERATURA", "HERRERA CACERES, CORA LISSETTE MÓDULO", "HERRERA CACERES, CORA LISSETTE MÓDULO"],
            ["9:30 AM - 10:15 AM", "AMAYA, LUIS MARIO IDIOMA EXTRANJERO", "GARCÍA NAVARRO, CARLOS HUMBERTO CIENCIAS NATURALES", "SARAVIA  DE YUDICE,EVELYN YANETH LENGUAJE Y LITERATURA", "HERRERA CACERES, CORA LISSETTE MÓDULO", "HERRERA CACERES, CORA LISSETTE MÓDULO"],
            ["10:15 AM - 10:30 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["10:30 AM - 11:15 PM", "AMAYA, LUIS MARIO IDIOMA EXTRANJERO", "HERRERA CACERES, CORA LISSETTE MÓDULO", "HERRERA CACERES, CORA LISSETTE MÓDULO", "AMAYA, LUIS MARIO IDIOMA EXTRANJERO", "HERRERA CACERES, CORA LISSETTE MÓDULO"],
            ["11:15 PM - 12:00 PM", "AMAYA, LUIS MARIO IDIOMA EXTRANJERO", "HERRERA CACERES, CORA LISSETTE MÓDULO", "HERRERA CACERES, CORA LISSETTE MÓDULO", "AMAYA, LUIS MARIO IDIOMA EXTRANJERO", "HERRERA CACERES, CORA LISSETTE MÓDULO"],
            ["12:00 PM - 1:00 PM",  "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["1:00 PM - 1:45 PM", "MARTÍNEZ  DE ELÍAS,CLAUDIA RAQUEL ESTUDIOS SOCIALES Y CÍVICA", "MORALES ROMERO, CÉSAR ALEJANDRO MATEMÁTICA", "AQUINO SÁNCHEZ, LORENA LISSETTE MOD 2.7 AC", "MORALES ROMERO, CÉSAR ALEJANDRO MATEMÁTICA", "LOBO DE OLIVA, MAGNOLIA DEL CARMEN MOD 2.6 AC"],
            ["1:45 PM - 2:30 PM", "MARTÍNEZ  DE ELÍAS,CLAUDIA RAQUEL ESTUDIOS SOCIALES Y CÍVICA", "MORALES ROMERO, CÉSAR ALEJANDRO MATEMÁTICA", "AQUINO SÁNCHEZ, LORENA LISSETTE MOD 2.7 AC", "MORALES ROMERO, CÉSAR ALEJANDRO MATEMÁTICA", "LOBO DE OLIVA, MAGNOLIA DEL CARMEN MOD 2.6 AC"],
            ["2:30 PM - 2:45 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["2:45 PM - 3:30 PM", "MARTÍNEZ  DE ELÍAS,CLAUDIA RAQUEL ESTUDIOS SOCIALES Y CÍVICA", "", "AQUINO SÁNCHEZ, LORENA LISSETTE MOD 2.7 AC", "MARTÍNEZ  DE ELÍAS,CLAUDIA RAQUEL ESTUDIOS SOCIALES Y CÍVICA", "MORALES ROMERO, CÉSAR ALEJANDRO MATEMÁTICA"],
            ["3:30 PM - 4:15 PM", "", "", "SARAVIA  DE YUDICE,EVELYN YANETH LENGUAJE Y LITERATURA", "MARTÍNEZ  DE ELÍAS,CLAUDIA RAQUEL ESTUDIOS SOCIALES Y CÍVICA", "MORALES ROMERO, CÉSAR ALEJANDRO MATEMÁTICA"],
            ["4:15 PM - 4:30 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["4:30 PM - 5:15 PM", "", "", "ESPINOZA RAMOS, RICARDO ADOLFO EDUCACIÓN FÍSICA", "", ""],
            ["5:15 PM - 6:00 PM", "", "", "ESPINOZA RAMOS, RICARDO ADOLFO EDUCACIÓN FÍSICA", "", ""],
        ],
        "2-2": [
             ["7:00 AM - 7:45 AM", "AMAYA, LUIS MARIO IDIOMA EXTRANJERO", "HERRERA CACERES, CORA LISSETTE MÓDULO", "HERRERA CACERES, CORA LISSETTE MÓDULO", "AMAYA, LUIS MARIO IDIOMA EXTRANJERO", "HERRERA CACERES, CORA LISSETTE MÓDULO"],
            ["7:45 AM - 8:30 AM", "AMAYA, LUIS MARIO IDIOMA EXTRANJERO", "HERRERA CACERES, CORA LISSETTE MÓDULO", "HERRERA CACERES, CORA LISSETTE MÓDULO", "AMAYA, LUIS MARIO IDIOMA EXTRANJERO", "HERRERA CACERES, CORA LISSETTE MÓDULO"],
            ["8:30 AM - 8:45 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["8:45 AM - 9:30 AM", "AMAYA, LUIS MARIO IDIOMA EXTRANJERO", "SARAVIA  DE YUDICE, EVELYN YANETH LENGUAJE Y LITERATURA", "HERRERA CACERES, CORA LISSETTE MÓDULO", "GARCÍA NAVARRO, CARLOS HUMBERTO CIENCIAS NATURALES", "MARTÍNEZ DE ALVARENGA,CLARINA ANGÉLICA ORIENTACIÓN PARA LA VIDA"],
            ["9:30 AM - 10:15 AM", "AMAYA, LUIS MARIO IDIOMA EXTRANJERO", "SARAVIA  DE YUDICE, EVELYN YANETH LENGUAJE Y LITERATURA", "HERRERA CACERES, CORA LISSETTE MÓDULO","GARCÍA NAVARRO, CARLOS HUMBERTO CIENCIAS NATURALES", "MARTÍNEZ DE ALVARENGA,CLARINA ANGÉLICA ORIENTACIÓN PARA LA VIDA"],
            ["10:15 AM - 10:30 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["10:30 AM - 11:15 PM", "HERRERA CACERES, CORA LISSETTE MÓDULO", "GARCÍA NAVARRO, CARLOS HUMBERTO CIENCIAS NATURALES", "GARCÍA NAVARRO, CARLOS HUMBERTO CIENCIAS NATURALES", "HERRERA CACERES, CORA LISSETTE MÓDULO", "SARAVIA  DE YUDICE,EVELYN YANETH LENGUAJE Y LITERATURA"],
            ["11:15 PM - 12:00 PM", "HERRERA CACERES, CORA LISSETTE MÓDULO", "GARCÍA NAVARRO, CARLOS HUMBERTO CIENCIAS NATURALES", "GARCÍA NAVARRO, CARLOS HUMBERTO CIENCIAS NATURALES", "HERRERA CACERES, CORA LISSETTE MÓDULO", ""],
            ["12:00 PM - 1:00 PM",  "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["1:00 PM - 1:45 PM", "BARRERA ORTEGA, MARIA ELENA ESTUDIOS SOCIALES Y CÍVICA", "LOBO DE OLIVA, MAGNOLIA DEL CARMEN MOD 2.6 AC", "BARRERA ORTEGA, MARIA ELENA ESTUDIOS SOCIALES Y CÍVICA", "AQUINO SÁNCHEZ, LORENA LISSETTE MOD 2.7 AC", ""],
            ["1:45 PM - 2:30 PM", "BARRERA ORTEGA, MARIA ELENA ESTUDIOS SOCIALES Y CÍVICA", "LOBO DE OLIVA, MAGNOLIA DEL CARMEN MOD 2.6 AC", "BARRERA ORTEGA, MARIA ELENA ESTUDIOS SOCIALES Y CÍVICA", "AQUINO SÁNCHEZ, LORENA LISSETTE MOD 2.7 AC", ""],
            ["2:30 PM - 2:45 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["2:45 PM - 3:30 PM", "MORALES ROMERO, CÉSAR ALEJANDRO MATEMÁTICA", "MORALES ROMERO, CÉSAR ALEJANDRO MATEMÁTICA", "BARRERA ORTEGA, MARIA ELENA ESTUDIOS SOCIALES Y CÍVICA", "AQUINO SÁNCHEZ, LORENA LISSETTE MOD 2.7 AC", ""],
            ["3:30 PM - 4:15 PM", "MORALES ROMERO, CÉSAR ALEJANDRO MATEMÁTICA", "MORALES ROMERO, CÉSAR ALEJANDRO MATEMÁTICA", "", "SARAVIA  DE YUDICE,EVELYN YANETH LENGUAJE Y LITERATURA", ""],
            ["4:15 PM - 4:30 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["4:30 PM - 5:15 PM", "", "ESPINOZA RAMOS, RICARDO ADOLFO EDUCACIÓN FÍSICA", "", "MORALES ROMERO, CÉSAR ALEJANDRO MATEMÁTICA", ""],
            ["5:15 PM - 6:00 PM", "", "ESPINOZA RAMOS, RICARDO ADOLFO EDUCACIÓN FÍSICA", "", "MORALES ROMERO, CÉSAR ALEJANDRO MATEMÁTICA", ""],
        ],
        
    },
    "tercero":{
        "3-1": [
             ["7:00 AM - 7:45 AM", "ARÉVALO CAÑAS, WILSON FABRICIO CONTABILIDAD BANCARIA Y SISTEMAS", "ANAYA RIVERA, ROXANA MARGARITA LABORATORIO DE CREATIVIDAD", "ARÉVALO CAÑAS, WILSON FABRICIO CONTABILIDAD BANCARIA Y SISTEMAS", "VILLALTA  DE GRANILLO,MAURA ELIZABETH COMERCIALIZACIÓN Y MERCADEO", "AQUINO SÁNCHEZ, LORENA LISSETTE PRÁCTICA"],
            ["7:45 AM - 8:30 AM", "ARÉVALO CAÑAS, WILSON FABRICIO CONTABILIDAD BANCARIA Y SISTEMAS", "ANAYA RIVERA, ROXANA MARGARITA LABORATORIO DE CREATIVIDAD", "ARÉVALO CAÑAS, WILSON FABRICIO CONTABILIDAD BANCARIA Y SISTEMAS", "VILLALTA  DE GRANILLO,MAURA ELIZABETH COMERCIALIZACIÓN Y MERCADEO", "AQUINO SÁNCHEZ, LORENA LISSETTE PRÁCTICA"],
            ["8:30 AM - 8:45 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["8:45 AM - 9:30 AM", "ARÉVALO CAÑAS, WILSON FABRICIO CONTABILIDAD BANCARIA Y SISTEMAS", "ARÉVALO CAÑAS, WILSON FABRICIO CONTABILIDAD BANCARIA Y SISTEMAS", "VILLALTA  DE GRANILLO,MAURA ELIZABETH TRABAJO DE GRADUACIÓN", "VILLALTA  DE GRANILLO,MAURA ELIZABETH COMERCIALIZACIÓN Y MERCADEO", "AQUINO SÁNCHEZ, LORENA LISSETTE PRÁCTICA"],
            ["9:30 AM - 10:15 AM", "ARÉVALO CAÑAS, WILSON FABRICIO CONTABILIDAD BANCARIA Y SISTEMAS", "ARÉVALO CAÑAS, WILSON FABRICIO CONTABILIDAD BANCARIA Y SISTEMAS", "VILLALTA  DE GRANILLO,MAURA ELIZABETH TRABAJO DE GRADUACIÓN", "AQUINO SÁNCHEZ, LORENA LISSETTE PRÁCTICA", "VILLALTA  DE GRANILLO,MAURA ELIZABETH PRESUPUESTO ANALISIS Y ECONOMIA"],
            ["10:15 AM - 10:30 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["10:30 AM - 11:15 PM", "VILLALTA  DE GRANILLO,MAURA ELIZABETH COMERCIALIZACIÓN Y MERCADEO", "VILLALTA  DE GRANILLO,MAURA ELIZABETH PRESUPUESTO ANALISIS Y ECONOMIA", "AQUINO SÁNCHEZ, LORENA LISSETTE PRÁCTICA PROFESIONAL", "AQUINO SÁNCHEZ, LORENA LISSETTE PRÁCTICA", "VILLALTA  DE GRANILLO,MAURA ELIZABETH PRESUPUESTO ANALISIS Y ECONOMIA"],
            ["11:15 PM - 12:00 PM", "VILLALTA  DE GRANILLO,MAURA ELIZABETH COMERCIALIZACIÓN Y MERCADEO", "VILLALTA  DE GRANILLO,MAURA ELIZABETH PRESUPUESTO ANALISIS Y ECONOMIA", "AQUINO SÁNCHEZ, LORENA LISSETTE PRÁCTICA PROFESIONAL", "AQUINO SÁNCHEZ, LORENA LISSETTE PRÁCTICA", "VILLALTA  DE GRANILLO,MAURA ELIZABETH PRESUPUESTO ANALISIS Y ECONOMIA"],
            ["12:00 PM - 1:00 PM",  "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["1:00 PM - 1:45 PM", "", "", "", "", ""],
            ["1:45 PM - 2:30 PM", "", "", "", "", ""],
            ["2:30 PM - 2:45 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["2:45 PM - 3:30 PM", "", "", "", "", ""],
            ["3:30 PM - 4:15 PM", "", "", "", "", ""],
            ["4:15 PM - 4:30 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["4:30 PM - 5:15 PM", "", "", "", "", ""],
            ["5:15 PM - 6:00 PM", "", "", "", "", ""],
        ],
        "3-2": [
             ["7:00 AM - 7:45 AM", "VILLALTA  DE GRANILLO,MAURA ELIZABETH PRESUPUESTO ANALISIS Y ECONOMIA", "VILLALTA  DE GRANILLO,MAURA ELIZABETH COMERCIALIZACIÓN Y MERCADEO", "VILLALTA  DE GRANILLO, MAURA ELIZABETH PRESUPUESTO ANALISIS Y ECONOMIA", "ARÉVALO CAÑAS, WILSON FABRICIO CONTABILIDAD BANCARIA Y SISTEMAS", "VILLALTA  DE GRANILLO, MAURA ELIZABETH TRABAJO DE GRADUACIÓN"],
            ["7:45 AM - 8:30 AM", "VILLALTA  DE GRANILLO,MAURA ELIZABETH PRESUPUESTO ANALISIS Y ECONOMIA", "VILLALTA  DE GRANILLO,MAURA ELIZABETH COMERCIALIZACIÓN Y MERCADEO", "VILLALTA  DE GRANILLO, MAURA ELIZABETH PRESUPUESTO ANALISIS Y ECONOMIA", "ARÉVALO CAÑAS, WILSON FABRICIO CONTABILIDAD BANCARIA Y SISTEMAS", "VILLALTA  DE GRANILLO, MAURA ELIZABETH TRABAJO DE GRADUACIÓN"],
            ["8:30 AM - 8:45 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["8:45 AM - 9:30 AM", "VILLALTA  DE GRANILLO,MAURA ELIZABETH PRESUPUESTO ANALISIS Y ECONOMIA", "VILLALTA  DE GRANILLO,MAURA ELIZABETH COMERCIALIZACIÓN Y MERCADEO", "ANAYA RIVERA, ROXANA MARGARITA LABORATORIO DE CREATIVIDAD", "ARÉVALO CAÑAS, WILSON FABRICIO CONTABILIDAD BANCARIA Y SISTEMAS", "ARÉVALO CAÑAS, WILSON FABRICIO CONTABILIDAD BANCARIA Y SISTEMAS"],
            ["9:30 AM - 10:15 AM", "AQUINO SÁNCHEZ, LORENA LISSETTE PRÁCTICA", "AQUINO SÁNCHEZ, LORENA LISSETTE PRÁCTICA", "ANAYA RIVERA, ROXANA MARGARITA LABORATORIO DE CREATIVIDAD", "ARÉVALO CAÑAS, WILSON FABRICIO CONTABILIDAD BANCARIA Y SISTEMAS", "ARÉVALO CAÑAS, WILSON FABRICIO CONTABILIDAD BANCARIA Y SISTEMAS"],
            ["10:15 AM - 10:30 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["10:30 AM - 11:15 PM", "AQUINO SÁNCHEZ, LORENA LISSETTE PRÁCTICA", "AQUINO SÁNCHEZ, LORENA LISSETTE PRÁCTICA", "ARÉVALO CAÑAS, WILSON FABRICIO CONTABILIDAD BANCARIA Y SISTEMAS", "VILLALTA  DE GRANILLO, MAURA ELIZABETH COMERCIALIZACIÓN Y MERCADEO", "AQUINO SÁNCHEZ, LORENA LISSETTE PRÁCTICA PROFESIONAL"],
            ["11:15 PM - 12:00 PM", "AQUINO SÁNCHEZ, LORENA LISSETTE PRÁCTICA", "AQUINO SÁNCHEZ, LORENA LISSETTE PRÁCTICA", "ARÉVALO CAÑAS, WILSON FABRICIO CONTABILIDAD BANCARIA Y SISTEMAS", "VILLALTA  DE GRANILLO, MAURA ELIZABETH COMERCIALIZACIÓN Y MERCADEO", "AQUINO SÁNCHEZ, LORENA LISSETTE PRÁCTICA PROFESIONAL"],
            ["12:00 PM - 1:00 PM",  "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["1:00 PM - 1:45 PM", "", "", "", "", ""],
            ["1:45 PM - 2:30 PM", "", "", "", "", ""],
            ["2:30 PM - 2:45 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["2:45 PM - 3:30 PM", "", "", "", "", ""],
            ["3:30 PM - 4:15 PM", "", "", "", "", ""],
            ["4:15 PM - 4:30 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["4:30 PM - 5:15 PM", "", "", "", "", ""],
            ["5:15 PM - 6:00 PM", "", "", "", "", ""],
        ],

    },
    
};

// Variables globales
let añoActual = "primero";
let seccionActual = "1-1";

// Cargar horario al iniciar la página
document.addEventListener('DOMContentLoaded', function() {
    cargarHorario(añoActual, seccionActual);
    configurarBotones();
});

// Configurar event listeners para los botones
function configurarBotones() {
    // Botones de año
    const botonesAño = document.querySelectorAll('.btn-year');
    botonesAño.forEach(boton => {
        boton.addEventListener('click', function() {
            botonesAño.forEach(btn => btn.classList.remove('active'));
            this.classList.add('active');
            
            añoActual = this.getAttribute('data-year');
            
            // Mostrar secciones correspondientes al año (CORREGIDO)
            document.querySelectorAll('.secciones').forEach(seccion => {
                seccion.style.display = 'none';
            });
            document.querySelector(`.secciones.${añoActual}`).style.display = 'flex';
            
            // Reiniciar sección actual y actualizar horario
            const primeraSeccion = document.querySelector(`.secciones.${añoActual} .btn-section`).getAttribute('data-section');
            seccionActual = primeraSeccion;
            
            // Actualizar botones de sección (CORREGIDO)
            document.querySelectorAll('.btn-section').forEach(boton => {
                boton.classList.remove('active');
            });
            document.querySelector(`.btn-section[data-section="${primeraSeccion}"]`).classList.add('active');
            
            // Cargar horario
            cargarHorario(añoActual, seccionActual);
            actualizarTitulo();
        });
    });
    
    // Botones de sección
    const botonesSeccion = document.querySelectorAll('.btn-section');
    botonesSeccion.forEach(boton => {
        boton.addEventListener('click', function() {
            botonesSeccion.forEach(btn => btn.classList.remove('active'));
            this.classList.add('active');
            
            seccionActual = this.getAttribute('data-section');
            cargarHorario(añoActual, seccionActual);
            actualizarTitulo();
        });
    });
}

// Cargar horario en la tabla
function cargarHorario(año, seccion) {
    const tbody = document.querySelector('.tabla-horario tbody');
    tbody.innerHTML = '';
    
    const horarioSeccion = horarios[año][seccion];
    
    if (horarioSeccion && horarioSeccion.length > 0) {
        horarioSeccion.forEach(fila => {
            const tr = document.createElement('tr');
            
            fila.forEach((celda, index) => {
                const td = document.createElement('td');
                td.textContent = celda;
                tr.appendChild(td);
            });
            
            tbody.appendChild(tr);
        });
    } else {
        // Mensaje si no hay horario disponible
        const tr = document.createElement('tr');
        const td = document.createElement('td');
        td.colSpan = 6;
        td.textContent = 'Horario no disponible para esta sección';
        td.style.textAlign = 'center';
        td.style.padding = '20px';
        tr.appendChild(td);
        tbody.appendChild(tr);
    }
}

// Actualizar título del horario
function actualizarTitulo() {
    const titulo = document.getElementById('titulo-seccion');
    const añoTexto = añoActual === 'primero' ? 'Primer Año' : 'Segundo Año';
    titulo.textContent = `${añoTexto} - Sección ${seccionActual}`;
}                                                                                                                                                                                                                                                                                                                                                                                                                   