const horarios = {
    "primero": {
        "1-1": [
            ["7:00 AM-7:45 AM", "BONILLA MANCIA, IMNA DINORA LENGUA Y LITERATURA", "CORTEZ HERNÁNDEZ, HERIBERTO FINANZAS Y ECONOMÍA", "CHÁVEZ RIVERA, MARTA ALICIA INGLÉS", "BONILLA MANCIA, IMNA DINORA LENGUA Y LITERATURA", ""],
            ["7:45 AM - 8:30 AM", "BONILLA MANCIA, IMNA DINORA LENGUA Y LITERATURA", "CORTEZ HERNÁNDEZ, HERIBERTO FINANZAS Y ECONOMÍA", "CHÁVEZ RIVERA, MARTA ALICIA INGLÉS", "BONILLA MANCIA, IMNA DINORA LENGUA Y LITERATURA", ""],
            ["8:30 AM - 8:45 AM", "Receso", "Receso", "Receso", "Receso", "Receso"],
            ["8:45 AM - 9:30 AM", "BONILLA MANCIA, IMNA DINORA LENGUA Y LITERATURA", "PÉREZ MARTÍNEZ, RENE ALFREDO EDUCACIÓN FÍSICA", "CAÑAS COREAS, WILFREDO BENJAMÍN CIENCIA Y TECNOLOGÍA", "CAÑAS COREAS, WILFREDO BENJAMÍN CIENCIA Y TECNOLOGÍA", ""],
            ["9:30 AM - 10:15 AM", "", "PÉREZ MARTÍNEZ, RENE ALFREDO EDUCACIÓN FÍSICA", "CAÑAS COREAS, WILFREDO BENJAMÍN CIENCIA Y TECNOLOGÍA", "CAÑAS COREAS, WILFREDO BENJAMÍN CIENCIA Y TECNOLOGÍA", ""],
            ["10:15 AM - 10:30 AM", "Receso", "Receso", "Receso", "Receso", "Receso"],
            ["10:30 AM - 11:15 PM", "CHÁVEZ RIVERA, MARTA ALICIA INGLÉS", "CAÑAS COREAS, WILFREDO BENJAMÍN CIENCIA Y TECNOLOGÍA", "", "CORTEZ HERNÁNDEZ, HERIBERTO FINANZAS Y ECONOMÍA", ""],
            ["11:15 PM - 12:00 PM", "CHÁVEZ RIVERA, MARTA ALICIA INGLÉS", "CAÑAS COREAS, WILFREDO BENJAMÍN CIENCIA Y TECNOLOGÍA", "", "CORTEZ HERNÁNDEZ, HERIBERTO FINANZAS Y ECONOMÍA", ""],
            ["12:00 PM - 1:00 PM",  "Receso", "Receso", "Receso", "Receso", "Receso"],
            ["1:00 PM - 1:45 PM", "", "CENTENO PORTILLO, MARIO ALFONSO PRECÁLCULO", "CENTENO PORTILLO, MARIO ALFONSO PRECÁLCULO", "Matemáticas", "AYALA RIVAS, JOSÉ UVALDO CIUDADANIA Y VALORES"],
            ["1:45 PM - 2:30 PM", "", "CENTENO PORTILLO, MARIO ALFONSO PRECÁLCULO", "CENTENO PORTILLO, MARIO ALFONSO PRECÁLCULO", "AYALA RIVAS, JOSÉ UVALDO CIUDADANIA Y VALORES", "AYALA RIVAS, JOSÉ UVALDO CIUDADANIA Y VALORES"],
            ["2:30 PM - 2:45 PM", "Receso", "Receso", "Receso", "Receso", "Receso"],
            ["2:45 PM - 3:30 PM", "", "", "AYALA RIVAS, JOSÉ UVALDO CIUDADANIA Y VALORES", "CENTENO PORTILLO, MARIO ALFONSO PRECÁLCULO", "MIRANDA CÓRDOVA, JOSÉ JAVIER CIENCIAS DE LA COMPUTACIÓN"],
            ["3:30 PM - 4:15 PM", "", "", "AYALA RIVAS, JOSÉ UVALDO CIUDADANIA Y VALORES", "CENTENO PORTILLO, MARIO ALFONSO PRECÁLCULO", "MIRANDA CÓRDOVA, JOSÉ JAVIER CIENCIAS DE LA COMPUTACIÓN"],
            ["4:15 PM - 4:30 PM", "Receso", "Receso", "Receso", "Receso", "Receso"],
            ["4:30 PM - 5:15 PM", "", "MIRANDA CÓRDOVA, JOSÉ JAVIER CIENCIAS DE LA COMPUTACIÓN", "", "", "GÓMEZ SERRANO, TELMA MARITZA PROYECTO DE VIDA Y CARRERA"],
            ["4:30 PM - 5:15 PM", "", "MIRANDA CÓRDOVA, JOSÉ JAVIER CIENCIAS DE LA COMPUTACIÓN", "", "", "GÓMEZ SERRANO, TELMA MARITZA PROYECTO DE VIDA Y CARRERA"],
        ],
        "1-2": [
            ["7:00 AM - 7:45 AM", "ZELAYA PÉREZ, ALISSON BERENICE MATEMÁTICA", "GUZMAN  DE NAVIDAD, FANNY PATRICIA IDIOMA EXTRANJERO", "MÉNDEZ TEJADA, ANA CECILIA LENGUAJE Y LITERATURA", "BONILLA MANCIA, IMNA DINORA LENGUA Y LITERATURA", "RIVERA ROMERO, SANDRA MARLENE CIENCIAS NATURALES"],
            ["7:45 AM - 8:30 AM", "ZELAYA PÉREZ, ALISSON BERENICE MATEMÁTICA", "GUZMAN  DE NAVIDAD, FANNY PATRICIA IDIOMA EXTRANJERO", "MÉNDEZ TEJADA, ANA CECILIA LENGUAJE Y LITERATURA", "BONILLA MANCIA, IMNA DINORA LENGUA Y LITERATURA", "RIVERA ROMERO, SANDRA MARLENE CIENCIAS NATURALES"],
            ["8:30 AM - 8:45 AM", "Receso", "Receso", "Receso", "Receso", "Receso"],
            ["8:45 AM - 9:30 AM", "RIVERA ROMERO, SANDRA MARLENE CIENCIAS NATURALES", "GUZMAN  DE NAVIDAD, FANNY PATRICIA IDIOMA EXTRANJERO", "MÉNDEZ TEJADA, ANA CECILIA LENGUAJE Y LITERATURA", "ZELAYA PÉREZ, ALISSON BERENICE MATEMÁTICA", "ZELAYA PÉREZ, ALISSON BERENICE MATEMÁTICA"],
            ["9:30 AM - 10:15 AM", "RIVERA ROMERO, SANDRA MARLENE CIENCIAS NATURALES", "ANAYA RIVERA, ROXANA MARGARITA ESTUDIOS SOCIALES Y CÍVICA", "LEÓN SILVA, YOLANDA ESTEFANIA FRANCÉS", "ZELAYA PÉREZ, ALISSON BERENICE MATEMÁTICA", "ZELAYA PÉREZ, ALISSON BERENICE MATEMÁTICA"],
            ["10:15 AM - 10:30 AM", "Receso", "Receso", "Receso", "Receso", "Receso"],
            ["10:30 AM - 11:15 PM", "", "ANAYA RIVERA, ROXANA MARGARITA ESTUDIOS SOCIALES Y CÍVICA", "LEÓN SILVA, YOLANDA ESTEFANIA FRANCÉS", "RIVERA ROMERO, SANDRA MARLENE CIENCIAS NATURALEs", "MÉNDEZ TEJADA, ANA CECILIA LENGUAJE Y LITERATURA"],
            ["11:15 PM - 12:00 PM", "", "ANAYA RIVERA, ROXANA MARGARITA ESTUDIOS SOCIALES Y CÍVICA", "LEÓN SILVA, YOLANDA ESTEFANIA FRANCÉS", "RIVERA ROMERO, SANDRA MARLENE CIENCIAS NATURALES", "MÉNDEZ TEJADA, ANA CECILIA LENGUAJE Y LITERATURA"],
            ["12:00 PM - 1:00 PM",  "Receso", "Receso", "Receso", "Receso", "Receso"],
            ["1:00 PM - 1:45 PM", "RIVAS MENDOZA, JOSÉ SAÚL CHL (BARTENDER)", "SARAVIA  DE YUDICE, EVELYN YANETH SEMINARIOS", "GÓMEZ SERRANO, TELMA MARITZA ORIENTACIÓN PARA LA VIDA", "ALVARADO DE MIRANDA, DENISSE ZORAIDA INFORMÁTICA", "SANTANA  LÓPEZ, ANA SELMA GEORGINA CHL (PANADERÍA Y PASTELERÍA)"],
            ["1:45 PM - 2:30 PM", "RIVAS MENDOZA, JOSÉ SAÚL CHL (BARTENDER)", "SARAVIA  DE YUDICE, EVELYN YANETH SEMINARIOS", "GÓMEZ SERRANO, TELMA MARITZA ORIENTACIÓN PARA LA VIDA", "ALVARADO DE MIRANDA, DENISSE ZORAIDA INFORMÁTICA", "SANTANA  LÓPEZ, ANA SELMA GEORGINA CHL (PANADERÍA Y PASTELERÍA)"],
            ["2:30 PM - 2:45 PM", "Receso", "Receso", "Receso", "Receso", "Receso"],
            ["2:45 PM - 3:30 PM", "ESPINOZA RAMOS, RICARDO ADOLFO EDUCACIÓN FÍSICA", "SARAVIA  DE YUDICE, EVELYN YANETH SEMINARIOS", "GÓMEZ SERRANO, TELMA MARITZA ORIENTACIÓN PARA LA VIDA", "ALVARADO DE MIRANDA, DENISSE ZORAIDA INFORMÁTICA", "SANTANA  LÓPEZ, ANA SELMA GEORGINA CHL (PANADERÍA Y PASTELERÍA)"],
            ["3:30 PM - 4:15 PM", "ESPINOZA RAMOS, RICARDO ADOLFO EDUCACIÓN FÍSICA", "", "", "", "SANTANA  LÓPEZ, ANA SELMA GEORGINA CHL (PANADERÍA Y PASTELERÍA)"],
            ["4:15 PM - 4:30 PM", "Receso", "Receso", "Receso", "Receso", "Receso"],
            ["4:30 PM - 5:15 PM", "", "", "", "", ""],
            ["4:30 PM - 5:15 PM", "", "", "", "", ""],
        ],

        "1-3": [
            ["7:00 AM - 7:45 AM", "", "GUARDADO MOJICA, MANOLO EDGARDO PRECÁLCULO", "GUARDADO MOJICA, MANOLO EDGARDO PRECÁLCULO", "CHÁVEZ RIVERA, MARTA ALICIA INGLÉS", "BONILLA MANCIA, IMNA DINORA LENGUA Y LITERATURA"],
            ["7:45 AM - 8:30 AM", "", "GUARDADO MOJICA, MANOLO EDGARDO PRECÁLCULO", "GUARDADO MOJICA, MANOLO EDGARDO PRECÁLCULO", "CHÁVEZ RIVERA, MARTA ALICIA INGLÉS", "BONILLA MANCIA, IMNA DINORA LENGUA Y LITERATURA"],
            ["8:30 AM - 8:45 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["8:45 AM - 9:30 AM", "", "LINARES MURGA, ANA CONCEPCIÓN SERVICIO SOCIAL ESTUDIANTIL", "CORTEZ HERNÁNDEZ, HERIBERTO FINANZAS Y ECONOMÍA", "GUARDADO MOJICA, MANOLO EDGARDO PRECÁLCULO", "CORTEZ HERNÁNDEZ, HERIBERTO FINANZAS Y ECONOMÍA"],
            ["9:30 AM - 10:15 AM", "","LINARES MURGA, ANA CONCEPCIÓN SERVICIO SOCIAL ESTUDIANTIL" ,"CORTEZ HERNÁNDEZ, HERIBERTO FINANZAS Y ECONOMÍA", "GUARDADO MOJICA, MANOLO EDGARDO PRECÁLCULO", "CORTEZ HERNÁNDEZ, HERIBERTO FINANZAS Y ECONOMÍA"],
            ["10:15 AM - 10:30 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["10:30 AM - 11:15 PM", "", "BONILLA MANCIA, IMNA DINORA LENGUA Y LITERATURA", "PÉREZ MARTÍNEZ, RENE ALFREDO EDUCACIÓN FÍSICA", "BONILLA MANCIA, IMNA DINORA LENGUA Y LITERATURA", "CHÁVEZ RIVERA, MARTA ALICIA INGLÉS"],
            ["11:15 PM - 12:00 PM", "", "BONILLA MANCIA, IMNA DINORA LENGUA Y LITERATURA", "PÉREZ MARTÍNEZ, RENE ALFREDO EDUCACIÓN FÍSICA", "", "CHÁVEZ RIVERA, MARTA ALICIA INGLÉS"],
            ["12:00 PM - 1:00 PM",  "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["1:00 PM - 1:45 PM", "AYALA RIVAS, JOSÉ UVALDO CIUDADANIA Y VALORES", "", "", "AYALA RIVAS, JOSÉ UVALDO CIUDADANIA Y VALORES", "MIRANDA CÓRDOVA, JOSÉ JAVIER CIENCIAS DE LA COMPUTACIÓN"],
            ["1:45 PM - 2:30 PM", "AYALA RIVAS, JOSÉ UVALDO CIUDADANIA Y VALORES", "", "", "", "MIRANDA CÓRDOVA, JOSÉ JAVIER CIENCIAS DE LA COMPUTACIÓN"],
            ["2:30 PM - 2:45 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["2:45 PM - 3:30 PM", "MENJIVAR LARIOS, BLANCA ARGENTINA CIENCIA Y TECNOLOGÍA", "", "", "MENJIVAR LARIOS, BLANCA ARGENTINA CIENCIA Y TECNOLOGÍA", "MENJIVAR LARIOS, BLANCA ARGENTINA CIENCIA Y TECNOLOGÍA"],
            ["3:30 PM - 4:15 PM", "MENJIVAR LARIOS, BLANCA ARGENTINA CIENCIA Y TECNOLOGÍA", "", "", "MENJIVAR LARIOS, BLANCA ARGENTINA CIENCIA Y TECNOLOGÍA", "MENJIVAR LARIOS, BLANCA ARGENTINA CIENCIA Y TECNOLOGÍA"],
            ["4:15 PM - 4:30 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["4:30 PM - 5:15 PM", "GÓMEZ SERRANO, TELMA MARITZA PROYECTO DE VIDA Y CARRERA", "", "", "MIRANDA CÓRDOVA, JOSÉ JAVIER CIENCIAS DE LA COMPUTACIÓN", "AYALA RIVAS, JOSÉ UVALDO CIUDADANIA Y VALORES"],
            ["5:15 PM - 6:00 PM", "GÓMEZ SERRANO, TELMA MARITZA PROYECTO DE VIDA Y CARRERA", "", "", "MIRANDA CÓRDOVA, JOSÉ JAVIER CIENCIAS DE LA COMPUTACIÓN", "AYALA RIVAS, JOSÉ UVALDO CIUDADANIA Y VALORES"],

        ],

        "1-4": [
            ["7:00 AM - 7:45 AM", "", "CAÑAS COREAS, WILFREDO BENJAMÍN CIENCIA Y TECNOLOGÍA", "PÉREZ MARTÍNEZ, RENE ALFREDO EDUCACIÓN FÍSICA", "SARAVIA  DE YUDICE, EVELYN YANETH LENGUA Y LITERATURA", "CORTEZ HERNÁNDEZ, HERIBERTO FINANZAS Y ECONOMÍA"],
            ["7:45 AM - 8:30 AM", "", "CAÑAS COREAS, WILFREDO BENJAMÍN CIENCIA Y TECNOLOGÍA", "PÉREZ MARTÍNEZ, RENE ALFREDO EDUCACIÓN FÍSICA", "SARAVIA  DE YUDICE, EVELYN YANETH LENGUA Y LITERATURA", "CORTEZ HERNÁNDEZ, HERIBERTO FINANZAS Y ECONOMÍA"],
            ["8:30 AM - 8:45 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["8:45 AM - 9:30 AM", "", "CORTEZ HERNÁNDEZ, HERIBERTO FINANZAS Y ECONOMÍA", "CHÁVEZ RIVERA, MARTA ALICIA INGLÉS", "SARAVIA  DE YUDICE, EVELYN YANETH LENGUA Y LITERATURA", "CHÁVEZ RIVERA, MARTA ALICIA INGLÉS"],
            ["9:30 AM - 10:15 AM", "", "CORTEZ HERNÁNDEZ, HERIBERTO FINANZAS Y ECONOMÍA", "CHÁVEZ RIVERA, MARTA ALICIA INGLÉS", "", "CHÁVEZ RIVERA, MARTA ALICIA INGLÉS"],
            ["10:15 AM - 10:30 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["10:30 AM - 11:15 PM", "", "SARAVIA  DE YUDICE, EVELYN YANETH LENGUA Y LITERATURA", "TOBAR  DE CÓRDOVA, CLAUDIA PATRICIA PROYECTO DE VIDA Y CARRERA", "CAÑAS COREAS, WILFREDO BENJAMÍN CIENCIA Y TECNOLOGÍA", "CAÑAS COREAS, WILFREDO BENJAMÍN CIENCIA Y TECNOLOGÍA"],
            ["11:15 PM - 12:00 PM", "", "SARAVIA  DE YUDICE, EVELYN YANETH LENGUA Y LITERATURA", "TOBAR  DE CÓRDOVA, CLAUDIA PATRICIA PROYECTO DE VIDA Y CARRERA", "CAÑAS COREAS, WILFREDO BENJAMÍN CIENCIA Y TECNOLOGÍA", "CAÑAS COREAS, WILFREDO BENJAMÍN CIENCIA Y TECNOLOGÍA"],
            ["12:00 PM - 1:00 PM",  "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["1:00 PM - 1:45 PM", "MELARA ESCAMILLA, RICARDO ERNESTO CIENCIAS DE LA COMPUTACIÓN", "", "", "CENTENO PORTILLO, MARIO ALFONSO PRECÁLCULO", "SOTO RIVERA, EDWIN ALEXANDER CIUDADANIA Y VALORES"],
            ["1:45 PM - 2:30 PM", "MELARA ESCAMILLA, RICARDO ERNESTO CIENCIAS DE LA COMPUTACIÓN", "", "", "CENTENO PORTILLO, MARIO ALFONSO PRECÁLCULO", "SOTO RIVERA, EDWIN ALEXANDER CIUDADANIA Y VALORES"],
            ["2:30 PM - 2:45 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["2:45 PM - 3:30 PM", "SOTO RIVERA, EDWIN ALEXANDER CIUDADANIA Y VALORES", "MELARA ESCAMILLA, RICARDO ERNESTO CIENCIAS DE LA COMPUTACIÓN", "", "", "SOTO RIVERA, EDWIN ALEXANDER CIUDADANIA Y VALORES"],
            ["3:30 PM - 4:15 PM", "SOTO RIVERA, EDWIN ALEXANDER CIUDADANIA Y VALORES", "MELARA ESCAMILLA, RICARDO ERNESTO CIENCIAS DE LA COMPUTACIÓN", "", "", ""],
            ["4:15 PM - 4:30 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["4:30 PM - 5:15 PM", "CENTENO PORTILLO, MARIO ALFONSO PRECÁLCULO", "", "", "", "CENTENO PORTILLO, MARIO ALFONSO PRECÁLCULO"],
            ["5:15 PM - 6:00 PM", "CENTENO PORTILLO, MARIO ALFONSO PRECÁLCULO", "", "", "", "CENTENO PORTILLO, MARIO ALFONSO PRECÁLCULO"],
        ],

        "1-5":[
            ["7:00 AM - 7:45 AM", "CAÑAS COREAS, WILFREDO BENJAMÍN CIENCIA Y TECNOLOGÍA", "", "CAÑAS COREAS, WILFREDO BENJAMÍN CIENCIA Y TECNOLOGÍA", "CAÑAS COREAS, WILFREDO BENJAMÍN CIENCIA Y TECNOLOGÍA", "SARAVIA  DE YUDICE, EVELYN YANETH LENGUA Y LITERATURA"],
            ["7:45 AM - 8:30 AM", "CAÑAS COREAS, WILFREDO BENJAMÍN CIENCIA Y TECNOLOGÍA", "", "CAÑAS COREAS, WILFREDO BENJAMÍN CIENCIA Y TECNOLOGÍA", "CAÑAS COREAS, WILFREDO BENJAMÍN CIENCIA Y TECNOLOGÍA", "SARAVIA  DE YUDICE, EVELYN YANETH LENGUA Y LITERATURA"],
            ["8:30 AM - 8:45 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["8:45 AM - 9:30 AM", "TOBAR  DE CÓRDOVA, CLAUDIA PATRICIA PROYECTO DE VIDA Y CARRERA", "", "PÉREZ MARTÍNEZ, RENE ALFREDO EDUCACIÓN FÍSICA", "", "SOLANO RIVERA, VICTORIA ELVIRA INGLÉS"],
            ["9:30 AM - 10:15 AM", "TOBAR  DE CÓRDOVA, CLAUDIA PATRICIA PROYECTO DE VIDA Y CARRERA", "", "PÉREZ MARTÍNEZ, RENE ALFREDO EDUCACIÓN FÍSICA", "SARAVIA  DE YUDICE, EVELYN YANETH LENGUA Y LITERATURA", "SOLANO RIVERA, VICTORIA ELVIRA INGLÉS"],
            ["10:15 AM - 10:30 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["10:30 AM - 11:15 PM", "ARÉVALO CAÑAS, WILSON FABRICIO FINANZAS Y ECONOMÍA", "", "", "SARAVIA  DE YUDICE, EVELYN YANETH LENGUA Y LITERATURA", "ARÉVALO CAÑAS, WILSON FABRICIO FINANZAS Y ECONOMÍA"],
            ["11:15 PM - 12:00 PM", "ARÉVALO CAÑAS, WILSON FABRICIO FINANZAS Y ECONOMÍA", "", "", "SARAVIA  DE YUDICE, EVELYN YANETH LENGUA Y LITERATURA", "ARÉVALO CAÑAS, WILSON FABRICIO FINANZAS Y ECONOMÍA"],
            ["12:00 PM - 1:00 PM",  "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["1:00 PM - 1:45 PM", "SOTO RIVERA, EDWIN ALEXANDER CIUDADANIA Y VALORES", "MELARA ESCAMILLA, RICARDO ERNESTO CIENCIAS DE LA COMPUTACIÓN", "SOLANO RIVERA, VICTORIA ELVIRA INGLÉS", "", "CENTENO PORTILLO, MARIO ALFONSO PRECÁLCULO"],
            ["1:45 PM - 2:30 PM", "SOTO RIVERA, EDWIN ALEXANDER CIUDADANIA Y VALORES", "MELARA ESCAMILLA, RICARDO ERNESTO CIENCIAS DE LA COMPUTACIÓN", "SOLANO RIVERA, VICTORIA ELVIRA INGLÉS", "", "CENTENO PORTILLO, MARIO ALFONSO PRECÁLCULO"],
            ["2:30 PM - 2:45 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["2:45 PM - 3:30 PM", "MELARA ESCAMILLA, RICARDO ERNESTO CIENCIAS DE LA COMPUTACIÓN", "CENTENO PORTILLO, MARIO ALFONSO PRECÁLCULO", "SOTO RIVERA, EDWIN ALEXANDER CIUDADANIA Y VALORES", "", ""],
            ["3:30 PM - 4:15 PM", "MELARA ESCAMILLA, RICARDO ERNESTO CIENCIAS DE LA COMPUTACIÓN", "CENTENO PORTILLO, MARIO ALFONSO PRECÁLCULO", "SOTO RIVERA, EDWIN ALEXANDER CIUDADANIA Y VALORES", "", ""],
            ["4:15 PM - 4:30 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["4:30 PM - 5:15 PM", "", "SOTO RIVERA, EDWIN ALEXANDER CIUDADANIA Y VALORES", "CENTENO PORTILLO, MARIO ALFONSO PRECÁLCULO", "", ""],
            ["5:15 PM - 6:00 PM", "", "", "CENTENO PORTILLO, MARIO ALFONSO PRECÁLCULO", "", ""],
        ],

        "1-6": [
            ["7:00 AM - 7:45 AM", "DÍAZ CALLEJAS, DAVID MAURICIOCIENCIAS DE LA COMPUTACIÓN", "ARÉVALO CAÑAS, WILSON FABRICIO FINANZAS Y ECONOMÍA", "", "PÉREZ MARTÍNEZ, RENE ALFREDO EDUCACIÓN FÍSICA", "ARÉVALO CAÑAS, WILSON FABRICIO FINANZAS Y ECONOMÍA"],
            ["7:45 AM - 8:30 AM", "DÍAZ CALLEJAS, DAVID MAURICIOCIENCIAS DE LACOMPUTACIÓN", "ARÉVALO CAÑAS, WILSON FABRICIO FINANZAS Y ECONOMÍA", "", "PÉREZ MARTÍNEZ, RENE ALFREDO EDUCACIÓN FÍSICA", "ARÉVALO CAÑAS, WILSON FABRICIO FINANZAS Y ECONOMÍA"],
            ["8:30 AM - 8:45 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["8:45 AM - 9:30 AM", "CAÑAS COREAS, WILFREDO BENJAMÍN CIENCIA Y TECNOLOGÍA", "CAÑAS COREAS, WILFREDO BENJAMÍN CIENCIA Y TECNOLOGÍA", "", "TOBAR  DE CÓRDOVA, CLAUDIA PATRICIA PROYECTO DE VIDA Y CARRERA", "CAÑAS COREAS, WILFREDO BENJAMÍN CIENCIA Y TECNOLOGÍA"],
            ["9:30 AM - 10:15 AM", "CAÑAS COREAS, WILFREDO BENJAMÍN CIENCIA Y TECNOLOGÍA", "CAÑAS COREAS, WILFREDO BENJAMÍN CIENCIA Y TECNOLOGÍA", "", "TOBAR  DE CÓRDOVA, CLAUDIA PATRICIA PROYECTO DE VIDA Y CARRERA", "CAÑAS COREAS, WILFREDO BENJAMÍN CIENCIA Y TECNOLOGÍA"],
            ["10:15 AM - 10:30 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["10:30 AM - 11:15 PM", "LINARES MURGA, ANA CONCEPCIÓN SERVICIO SOCIAL ESTUDIANTIL", "", "", "DÍAZ CALLEJAS, DAVID MAURICIO CIENCIAS DE LA COMPUTACIÓN", "SOLANO RIVERA, VICTORIA ELVIRA INGLÉS"],
            ["11:15 PM - 12:00 PM", "LINARES MURGA, ANA CONCEPCIÓN SERVICIO SOCIAL ESTUDIANTIL", "", "", "DÍAZ CALLEJAS, DAVID MAURICIO CIENCIAS DE LA COMPUTACIÓN", "SOLANO RIVERA, VICTORIA ELVIRA INGLÉS"],
            ["12:00 PM - 1:00 PM",  "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["1:00 PM - 1:45 PM", "SARAVIA  DE YUDICE, EVELYN YANETH LENGUA Y LITERATURA", "SOTO RIVERA, EDWIN ALEXANDER CIUDADANIA Y VALORES", "SOTO RIVERA, EDWIN ALEXANDER CIUDADANIA Y VALORES", "", ""],
            ["1:45 PM - 2:30 PM", "SARAVIA  DE YUDICE, EVELYN YANETH LENGUA Y LITERATURA", "SOTO RIVERA, EDWIN ALEXANDER CIUDADANIA Y VALORES", "SOTO RIVERA, EDWIN ALEXANDER CIUDADANIA Y VALORES", "", ""],
            ["2:30 PM - 2:45 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["2:45 PM - 3:30 PM", "CENTENO PORTILLO, MARIO ALFONSO PRECÁLCULO", "SOTO RIVERA, EDWIN ALEXANDER CIUDADANIA Y VALORES", "CENTENO PORTILLO, MARIO ALFONSO PRECÁLCULO", "", ""],
            ["3:30 PM - 4:15 PM", "CENTENO PORTILLO, MARIO ALFONSO PRECÁLCULO", "SOTO RIVERA, EDWIN ALEXANDER CIUDADANIA Y VALORES", "CENTENO PORTILLO, MARIO ALFONSO PRECÁLCULO", "", ""],
            ["4:15 PM - 4:30 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["4:30 PM - 5:15 PM", "SOLANO RIVERA, VICTORIA ELVIRA INGLÉS", "CENTENO PORTILLO, MARIO ALFONSO PRECÁLCULO", "SARAVIA  DE YUDICE, EVELYN YANETH LENGUA Y LITERATURA", "", ""],
            ["5:15 PM - 6:00 PM", "SOLANO RIVERA, VICTORIA ELVIRA INGLÉS", "CENTENO PORTILLO, MARIO ALFONSO PRECÁLCULO", "SARAVIA  DE YUDICE, EVELYN YANETH LENGUA Y LITERATURA", "", ""],

        ],
        
        "1-7": [
            ["7:00 AM - 7:45 AM", "PÉREZ MARTÍNEZ, RENE ALFREDO EDUCACIÓN FÍSICA", "BONILLA MANCIA, IMNA DINORA LENGUA Y LITERATURA", "", "GUARDADO MOJICA, MANOLO EDGARDO PRECÁLCULO", "MENJIVAR LARIOS, BLANCA ARGENTINA CIENCIA Y TECNOLOGÍA"],
            ["7:45 AM - 8:30 AM", "PÉREZ MARTÍNEZ, RENE ALFREDO EDUCACIÓN FÍSICA", "BONILLA MANCIA, IMNA DINORA LENGUA Y LITERATURA", "", "GUARDADO MOJICA, MANOLO EDGARDO PRECÁLCULO", "MENJIVAR LARIOS, BLANCA ARGENTINA CIENCIA Y TECNOLOGÍA"],
            ["8:30 AM - 8:45 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["8:45 AM - 9:30 AM", "GUARDADO MOJICA, MANOLO EDGARDO PRECÁLCULO", "BONILLA MANCIA, IMNA DINORA LENGUA Y LITERATURA", "", "BONILLA MANCIA, IMNA DINORA LENGUA Y LITERATURA", "GUARDADO MOJICA, MANOLO EDGARDO PRECÁLCULO"],
            ["9:30 AM - 10:15 AM", "GUARDADO MOJICA, MANOLO EDGARDO PRECÁLCULO", "", "", "BONILLA MANCIA, IMNA DINORA LENGUA Y LITERATURA", "GUARDADO MOJICA, MANOLO EDGARDO PRECÁLCULO"],
            ["10:15 AM - 10:30 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["10:30 AM - 11:15 PM", "CORTEZ HERNÁNDEZ, HERIBERTO FINANZAS Y ECONOMÍA", "CHÁVEZ RIVERA, MARTA ALICIA INGLÉS", "", "CHÁVEZ RIVERA, MARTA ALICIA INGLÉS", "CORTEZ HERNÁNDEZ, HERIBERTO FINANZAS Y ECONOMÍA"],
            ["11:15 PM - 12:00 PM", "CORTEZ HERNÁNDEZ, HERIBERTO FINANZAS Y ECONOMÍA", "CHÁVEZ RIVERA, MARTA ALICIA INGLÉS", "", "CHÁVEZ RIVERA, MARTA ALICIA INGLÉS", "CORTEZ HERNÁNDEZ, HERIBERTO FINANZAS Y ECONOMÍA"],
            ["12:00 PM - 1:00 PM",  "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["1:00 PM - 1:45 PM", "MENJIVAR LARIOS, BLANCA ARGENTINA CIENCIA Y TECNOLOGÍA", "MIRANDA CÓRDOVA, JOSÉ JAVIER CIENCIAS DE LA COMPUTACIÓN", "AYALA RIVAS, JOSÉ UVALDO CIUDADANIA Y VALORES", "", ""],
            ["1:45 PM - 2:30 PM", "MENJIVAR LARIOS, BLANCA ARGENTINA CIENCIA Y TECNOLOGÍA", "MIRANDA CÓRDOVA, JOSÉ JAVIER CIENCIAS DE LA COMPUTACIÓN", "AYALA RIVAS, JOSÉ UVALDO CIUDADANIA Y VALORES", "", ""],
            ["2:30 PM - 2:45 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["2:45 PM - 3:30 PM", "AYALA RIVAS, JOSÉ UVALDO CIUDADANIA Y VALORES", "MENJIVAR LARIOS, BLANCA ARGENTINA CIENCIA Y TECNOLOGÍA", "MIRANDA CÓRDOVA, JOSÉ JAVIER CIENCIAS DE LA COMPUTACIÓN", "", ""],
            ["3:30 PM - 4:15 PM", "AYALA RIVAS, JOSÉ UVALDO CIUDADANIA Y VALORES", "MENJIVAR LARIOS, BLANCA ARGENTINA CIENCIA Y TECNOLOGÍA", "MIRANDA CÓRDOVA, JOSÉ JAVIER CIENCIAS DE LA COMPUTACIÓN", "", ""],
            ["4:15 PM - 4:30 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["4:30 PM - 5:15 PM", "AYALA RIVAS, JOSÉ UVALDO CIUDADANIA Y VALORES", "", "GÓMEZ SERRANO, TELMA MARITZA PROYECTO DE VIDA Y CARRERA", "", ""],
            ["5:15 PM - 6:00 PM", "", "", "GÓMEZ SERRANO, TELMA MARITZA PROYECTO DE VIDA Y CARRERA", "", ""],
        ],

        "1-8": [
            ["7:00 AM - 7:45 AM", "DÍAZ CALLEJAS, DAVID MAURICIO CIENCIAS DE LA COMPUTACIÓN", "ARÉVALO CAÑAS, WILSON FABRICIO FINANZAS Y ECONOMÍA", "", "PÉREZ MARTÍNEZ, RENE ALFREDO EDUCACIÓN FÍSICA", "ARÉVALO CAÑAS, WILSON FABRICIO FINANZAS Y ECONOMÍA"],
            ["7:45 AM - 8:30 AM", "DÍAZ CALLEJAS, DAVID MAURICIO CIENCIAS DE LA COMPUTACIÓN", "ARÉVALO CAÑAS, WILSON FABRICIO FINANZAS Y ECONOMÍA", "", "PÉREZ MARTÍNEZ, RENE ALFREDO EDUCACIÓN FÍSICA", "ARÉVALO CAÑAS, WILSON FABRICIO FINANZAS Y ECONOMÍA"],
            ["8:30 AM - 8:45 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["8:45 AM - 9:30 AM", "CAÑAS COREAS, WILFREDO BENJAMÍN CIENCIA Y TECNOLOGÍA", "CAÑAS COREAS, WILFREDO BENJAMÍN CIENCIA Y TECNOLOGÍA", "", "TOBAR  DE CÓRDOVA, CLAUDIA PATRICIA PROYECTO DE VIDA Y CARRERA", "CAÑAS COREAS, WILFREDO BENJAMÍN CIENCIA Y TECNOLOGÍA"],
            ["9:30 AM - 10:15 AM", "CAÑAS COREAS, WILFREDO BENJAMÍN CIENCIA Y TECNOLOGÍA", "CAÑAS COREAS, WILFREDO BENJAMÍN CIENCIA Y TECNOLOGÍA", "", "TOBAR  DE CÓRDOVA, CLAUDIA PATRICIA PROYECTO DE VIDA Y CARRERA", "CAÑAS COREAS, WILFREDO BENJAMÍN CIENCIA Y TECNOLOGÍA"],
            ["10:15 AM - 10:30 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["10:30 AM - 11:15 PM", "TOBAR  DE CÓRDOVA, CLAUDIA PATRICIA PROYECTO DE VIDA Y CARRERA", "", "", "DÍAZ CALLEJAS, DAVID MAURICIO CIENCIAS DE LA COMPUTACIÓN", "SOLANO RIVERA, VICTORIA ELVIRA INGLÉS"],
            ["11:15 PM - 12:00 PM", "TOBAR  DE CÓRDOVA, CLAUDIA PATRICIA PROYECTO DE VIDA Y CARRERA", "", "", "DÍAZ CALLEJAS, DAVID MAURICIO CIENCIAS DE LA COMPUTACIÓN", "SOLANO RIVERA, VICTORIA ELVIRA INGLÉS"],
            ["12:00 PM - 1:00 PM",  "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["1:00 PM - 1:45 PM", "SARAVIA  DE YUDICE, EVELYN YANETH LENGUA Y LITERATURA", "SOTO RIVERA, EDWIN ALEXANDER CIUDADANIA Y VALORES", "SOTO RIVERA, EDWIN ALEXANDER CIUDADANIA Y VALORES", "", ""],
            ["1:45 PM - 2:30 PM", "SARAVIA  DE YUDICE, EVELYN YANETH LENGUA Y LITERATURA", "SOTO RIVERA, EDWIN ALEXANDER CIUDADANIA Y VALORES", "SOTO RIVERA, EDWIN ALEXANDER CIUDADANIA Y VALORES", "", ""],
            ["2:30 PM - 2:45 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["2:45 PM - 3:30 PM", "CENTENO PORTILLO, MARIO ALFONSO PRECÁLCULO", "SOTO RIVERA, EDWIN ALEXANDER CIUDADANIA Y VALORES", "CENTENO PORTILLO, MARIO ALFONSO PRECÁLCULO", "", ""],
            ["3:30 PM - 4:15 PM", "CENTENO PORTILLO, MARIO ALFONSO PRECÁLCULO", "SOTO RIVERA, EDWIN ALEXANDER CIUDADANIA Y VALORES", "CENTENO PORTILLO, MARIO ALFONSO PRECÁLCULO", "", ""],
            ["4:15 PM - 4:30 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["4:30 PM - 5:15 PM", "SOLANO RIVERA, VICTORIA ELVIRA INGLÉS", "CENTENO PORTILLO, MARIO ALFONSO PRECÁLCULO", "SARAVIA  DE YUDICE, EVELYN YANETH LENGUA Y LITERATURA", "", ""],
            ["5:15 PM - 6:00 PM", "SOLANO RIVERA, VICTORIA ELVIRA INGLÉS", "CENTENO PORTILLO, MARIO ALFONSO PRECÁLCULO", "SARAVIA  DE YUDICE, EVELYN YANETH LENGUA Y LITERATURA", "", ""],

        ]
    },
    "segundo": {
        "2-1": [
            ["7:00 AM - 7:45 AM", "ZELAYA PÉREZ, ALISSON BERENICE MATEMÁTICA", "GUZMAN  DE NAVIDAD, FANNY PATRICIA IDIOMA EXTRANJERO", "MÉNDEZ TEJADA, ANA CECILIA LENGUAJE Y LITERATURA", "ANAYA RIVERA, ROXANA MARGARITA ESTUDIOS SOCIALES Y CÍVICA", "RIVERA ROMERO, SANDRA MARLENE CIENCIAS NATURALES"],
            ["7:45 AM - 8:30 AM", "ZELAYA PÉREZ, ALISSON BERENICE MATEMÁTICA", "GUZMAN  DE NAVIDAD, FANNY PATRICIA IDIOMA EXTRANJERO", "MÉNDEZ TEJADA, ANA CECILIA LENGUAJE Y LITERATURA", "ANAYA RIVERA, ROXANA MARGARITA ESTUDIOS SOCIALES Y CÍVICA", "RIVERA ROMERO, SANDRA MARLENE CIENCIAS NATURALES"],
            ["8:30 AM - 8:45 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["8:45 AM - 9:30 AM", "RIVERA ROMERO, SANDRA MARLENE CIENCIAS NATURALES", "GUZMAN  DE NAVIDAD, FANNY PATRICIA IDIOMA EXTRANJERO", "MÉNDEZ TEJADA, ANA CECILIA LENGUAJE Y LITERATURA", "ZELAYA PÉREZ, ALISSON BERENICE MATEMÁTICA", "ZELAYA PÉREZ, ALISSON BERENICE MATEMÁTICA"],
            ["9:30 AM - 10:15 AM", "RIVERA ROMERO, SANDRA MARLENE CIENCIAS NATURALES", "GUZMAN  DE NAVIDAD, FANNY PATRICIA IDIOMA EXTRANJERO", "MÉNDEZ TEJADA, ANA CECILIA LENGUAJE Y LITERATURA", "ZELAYA PÉREZ, ALISSON BERENICE MATEMÁTICA", "ZELAYA PÉREZ, ALISSON BERENICE MATEMÁTICA"],
            ["10:15 AM - 10:30 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["10:30 AM - 11:15 PM", "", "ANAYA RIVERA, ROXANA MARGARITA ESTUDIOS SOCIALES Y CÍVICA", "LEÓN SILVA, YOLANDA ESTEFANIA FRANCÉS", "RIVERA ROMERO, SANDRA MARLENE CIENCIAS NATURALES", "MÉNDEZ TEJADA, ANA CECILIA LENGUAJE Y LITERATURA"],
            ["11:15 PM - 12:00 PM", "", "ANAYA RIVERA, ROXANA MARGARITA ESTUDIOS SOCIALES Y CÍVICA", "LEÓN SILVA, YOLANDA ESTEFANIA FRANCÉS", "RIVERA ROMERO, SANDRA MARLENE CIENCIAS NATURALES", "MÉNDEZ TEJADA, ANA CECILIA LENGUAJE Y LITERATURA"],
            ["12:00 PM - 1:00 PM",  "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["1:00 PM - 1:45 PM", "RIVAS MENDOZA, JOSÉ SAÚL CHL (BARTENDER)", "SARAVIA  DE YUDICE, EVELYN YANETH SEMINARIOS", "GÓMEZ SERRANO, TELMA MARITZA ORIENTACIÓN PARA LA VIDA", "ALVARADO DE MIRANDA, DENISSE ZORAIDA INFORMÁTICA", "SANTANA  LÓPEZ, ANA SELMA GEORGINA CHL (PANADERÍA Y PASTELERÍA)"],
            ["1:45 PM - 2:30 PM", "RIVAS MENDOZA, JOSÉ SAÚL CHL (BARTENDER)", "SARAVIA  DE YUDICE, EVELYN YANETH SEMINARIOS", "GÓMEZ SERRANO, TELMA MARITZA ORIENTACIÓN PARA LA VIDA", "ALVARADO DE MIRANDA, DENISSE ZORAIDA INFORMÁTICA", "SANTANA  LÓPEZ, ANA SELMA GEORGINA CHL (PANADERÍA Y PASTELERÍA)"],
            ["2:30 PM - 2:45 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["2:45 PM - 3:30 PM", "ESPINOZA RAMOS, RICARDO ADOLFO EDUCACIÓN FÍSICA", "SARAVIA  DE YUDICE, EVELYN YANETH SEMINARIOS", "GÓMEZ SERRANO, TELMA MARITZA ORIENTACIÓN PARA LA VIDA", "ALVARADO DE MIRANDA, DENISSE ZORAIDA INFORMÁTICA", "SANTANA  LÓPEZ, ANA SELMA GEORGINA CHL (PANADERÍA Y PASTELERÍA)"],
            ["3:30 PM - 4:15 PM", "ESPINOZA RAMOS, RICARDO ADOLFO EDUCACIÓN FÍSICA", "", "", "", "SANTANA  LÓPEZ, ANA SELMA GEORGINA CHL (PANADERÍA Y PASTELERÍA)"],
            ["4:15 PM - 4:30 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["4:30 PM - 5:15 PM", "", "", "", "", ""],
            ["5:15 PM - 6:00 PM", "", "", "", "", ""],

        ],

        "2-2": [
            ["7:00 AM - 7:45 AM", "MÉNDEZ TEJADA, ANA CECILIA LENGUAJE Y LITERATURA", "RIVERA ROMERO, SANDRA MARLENE CIENCIAS NATURALES", "ANAYA RIVERA, ROXANA MARGARITA ESTUDIOS SOCIALES Y CÍVICA", "RIVERA ROMERO, SANDRA MARLENE CIENCIAS NATURALES", "ANAYA RIVERA, ROXANA MARGARITA ESTUDIOS SOCIALES Y CÍVICA"],
            ["7:45 AM - 8:30 AM", "MÉNDEZ TEJADA, ANA CECILIA LENGUAJE Y LITERATURA", "RIVERA ROMERO, SANDRA MARLENE CIENCIAS NATURALES", "ANAYA RIVERA, ROXANA MARGARITA ESTUDIOS SOCIALES Y CÍVICA", "RIVERA ROMERO, SANDRA MARLENE CIENCIAS NATURALES", "ANAYA RIVERA, ROXANA MARGARITA ESTUDIOS SOCIALES Y CÍVICA"],
            ["8:30 AM - 8:45 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["8:45 AM - 9:30 AM", "MÉNDEZ TEJADA, ANA CECILIA LENGUAJE Y LITERATURA", "ZELAYA PÉREZ, ALISSON BERENICE MATEMÁTICA", "RIVERA ROMERO, SANDRA MARLENE CIENCIAS NATURALES", "LEÓN SILVA, YOLANDA ESTEFANIA FRANCÉS", "ANAYA RIVERA, ROXANA MARGARITA ESTUDIOS SOCIALES Y CÍVICA"],
            ["9:30 AM - 10:15 AM", "MÉNDEZ TEJADA, ANA CECILIA LENGUAJE Y LITERATURA", "ZELAYA PÉREZ, ALISSON BERENICE MATEMÁTICA", "RIVERA ROMERO, SANDRA MARLENE CIENCIAS NATURALES", "LEÓN SILVA, YOLANDA ESTEFANIA FRANCÉS", ""],
            ["10:15 AM - 10:30 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["10:30 AM - 11:15 PM", "GUZMAN  DE NAVIDAD, FANNY PATRICIA IDIOMA EXTRANJERO", "MÉNDEZ TEJADA, ANA CECILIA LENGUAJE Y LITERATURA", "ZELAYA PÉREZ, ALISSON BERENICE MATEMÁTICA", "LEÓN SILVA, YOLANDA ESTEFANIA FRANCÉS", "ZELAYA PÉREZ, ALISSON BERENICE MATEMÁTICA"],
            ["11:15 PM - 12:00 PM", "GUZMAN  DE NAVIDAD, FANNY PATRICIA IDIOMA EXTRANJERO", "MÉNDEZ TEJADA, ANA CECILIA LENGUAJE Y LITERATURA", "ZELAYA PÉREZ, ALISSON BERENICE MATEMÁTICA", "", "ZELAYA PÉREZ, ALISSON BERENICE MATEMÁTICA"],
            ["12:00 PM - 1:00 PM",  "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["1:00 PM - 1:45 PM", "ESPINOZA RAMOS, RICARDO ADOLFO EDUCACIÓN FÍSICA", "ALVARADO DE MIRANDA, DENISSE ZORAIDA INFORMÁTICA", "SANTANA  LÓPEZ, ANA SELMA GEORGINA CHL (PANADERÍA Y PASTELERÍA)", "GÓMEZ SERRANO, TELMA MARITZA ORIENTACIÓN PARA LA VIDA", "SARAVIA  DE YUDICE, EVELYN YANETH SEMINARIOS"],
            ["1:45 PM - 2:30 PM", "ESPINOZA RAMOS, RICARDO ADOLFO EDUCACIÓN FÍSICA", "ALVARADO DE MIRANDA, DENISSE ZORAIDA INFORMÁTICA", "SANTANA  LÓPEZ, ANA SELMA GEORGINA CHL (PANADERÍA Y PASTELERÍA)", "GÓMEZ SERRANO, TELMA MARITZA ORIENTACIÓN PARA LA VIDA", "SARAVIA  DE YUDICE, EVELYN YANETH SEMINARIOS"],
            ["2:30 PM - 2:45 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["2:45 PM - 3:30 PM", "RIVAS MENDOZA, JOSÉ SAÚL CHL (BARTENDER)", "ALVARADO DE MIRANDA, DENISSE ZORAIDA INFORMÁTICA", "SANTANA  LÓPEZ, ANA SELMA GEORGINA CHL (PANADERÍA Y PASTELERÍA)", "", ""],
            ["3:30 PM - 4:15 PM", "RIVAS MENDOZA, JOSÉ SAÚL CHL (BARTENDER)", "", "SANTANA  LÓPEZ, ANA SELMA GEORGINA CHL (PANADERÍA Y PASTELERÍA)", "GÓMEZ SERRANO, TELMA MARITZA ORIENTACIÓN PARA LA VIDA", "SARAVIA  DE YUDICE, EVELYN YANETH SEMINARIOS"],
            ["4:15 PM - 4:30 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["4:30 PM - 5:15 PM", "", "", "", "", ""],
            ["5:15 PM - 6:00 PM", "", "", "", "", ""],

        ],

       "2-3": [
            ["7:00 AM - 7:45 AM", "RIVERA ROMERO, SANDRA MARLENE CIENCIAS NATURALES", "ZELAYA PÉREZ, ALISSON BERENICE MATEMÁTICA", "LEÓN SILVA, YOLANDA ESTEFANIA FRANCÉS", "MÉNDEZ TEJADA, ANA CECILIA LENGUAJE Y LITERATURA", "ZELAYA PÉREZ, ALISSON BERENICE MATEMÁTICA"],
            ["7:45 AM - 8:30 AM", "RIVERA ROMERO, SANDRA MARLENE CIENCIAS NATURALES", "ZELAYA PÉREZ, ALISSON BERENICE MATEMÁTICA", "LEÓN SILVA, YOLANDA ESTEFANIA FRANCÉS", "MÉNDEZ TEJADA, ANA CECILIA LENGUAJE Y LITERATURA", "ZELAYA PÉREZ, ALISSON BERENICE MATEMÁTICA"],
            ["8:30 AM - 8:45 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["8:45 AM - 9:30 AM", "ZELAYA PÉREZ, ALISSON BERENICE MATEMÁTICA", "MÉNDEZ TEJADA, ANA CECILIA LENGUAJE Y LITERATURA", "LEÓN SILVA, YOLANDA ESTEFANIA FRANCÉS", "MÉNDEZ TEJADA, ANA CECILIA LENGUAJE Y LITERATURA", "RIVERA ROMERO, SANDRA MARLENE CIENCIAS NATURALES"],
            ["9:30 AM - 10:15 AM", "ZELAYA PÉREZ, ALISSON BERENICE MATEMÁTICA", "MÉNDEZ TEJADA, ANA CECILIA LENGUAJE Y LITERATURA", "GUZMAN  DE NAVIDAD, FANNY PATRICIA IDIOMA EXTRANJERO", "ANAYA RIVERA, ROXANA MARGARITA ESTUDIOS SOCIALES Y CÍVICA", "RIVERA ROMERO, SANDRA MARLENE CIENCIAS NATURALES"],
            ["10:15 AM - 10:30 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["10:30 AM - 11:15 PM", "ANAYA RIVERA, ROXANA MARGARITA ESTUDIOS SOCIALES Y CÍVICA", "RIVERA ROMERO, SANDRA MARLENE CIENCIAS NATURALES", "GUZMAN  DE NAVIDAD, FANNY PATRICIA IDIOMA EXTRANJERO", "ANAYA RIVERA, ROXANA MARGARITA ESTUDIOS SOCIALES Y CÍVICA", ""],
            ["11:15 PM - 12:00 PM", "ANAYA RIVERA, ROXANA MARGARITA ESTUDIOS SOCIALES Y CÍVICA", "RIVERA ROMERO, SANDRA MARLENE CIENCIAS NATURALES", "GUZMAN  DE NAVIDAD, FANNY PATRICIA IDIOMA EXTRANJERO", "ANAYA RIVERA, ROXANA MARGARITA ESTUDIOS SOCIALES Y CÍVICA", ""],
            ["12:00 PM - 1:00 PM",  "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["1:00 PM - 1:45 PM", "SANTANA  LÓPEZ, ANA SELMA GEORGINA CHL (PANADERÍA Y PASTELERÍA)", "GÓMEZ SERRANO, TELMA MARITZA ORIENTACIÓN PARA LA VIDA", "SARAVIA  DE YUDICE, EVELYN YANETH SEMINARIOS", "MELARA ESCAMILLA, RICARDO ERNESTO INFORMÁTICA", "ESPINOZA RAMOS, RICARDO ADOLFO EDUCACIÓN FÍSICA"],
            ["1:45 PM - 2:30 PM", "SANTANA  LÓPEZ, ANA SELMA GEORGINA CHL (PANADERÍA Y PASTELERÍA)", "GÓMEZ SERRANO, TELMA MARITZA ORIENTACIÓN PARA LA VIDA", "SARAVIA  DE YUDICE, EVELYN YANETH SEMINARIOS", "MELARA ESCAMILLA, RICARDO ERNESTO INFORMÁTICA", "ESPINOZA RAMOS, RICARDO ADOLFO EDUCACIÓN FÍSICA"],
            ["2:30 PM - 2:45 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["2:45 PM - 3:30 PM", "SANTANA  LÓPEZ, ANA SELMA GEORGINA CHL (PANADERÍA Y PASTELERÍA)", "GÓMEZ SERRANO, TELMA MARITZA ORIENTACIÓN PARA LA VIDA", "SARAVIA  DE YUDICE, EVELYN YANETH SEMINARIOS", "MELARA ESCAMILLA, RICARDO ERNESTO INFORMÁTICA", "RIVAS MENDOZA, JOSÉ SAÚL CHL (BARTENDER)"],
            ["3:30 PM - 4:15 PM", "SANTANA  LÓPEZ, ANA SELMA GEORGINA CHL (PANADERÍA Y PASTELERÍA)", "", "", "", "RIVAS MENDOZA, JOSÉ SAÚL CHL (BARTENDER)"],
            ["4:15 PM - 4:30 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["4:30 PM - 5:15 PM", "", "", "", "", ""],
            ["5:15 PM - 6:00 PM", "", "", "", "", ""],

        ],

        "2-4": [
            ["7:00 AM - 7:45 AM", "GUZMAN  DE NAVIDAD, FANNY PATRICIA IDIOMA EXTRANJERO", "LEÓN SILVA, YOLANDA ESTEFANIA FRANCÉS", "RIVERA ROMERO, SANDRA MARLENE CIENCIAS NATURALES", "ZELAYA PÉREZ, ALISSON BERENICE MATEMÁTICA", "MÉNDEZ TEJADA, ANA CECILIA LENGUAJE Y LITERATURA"],
            ["7:45 AM - 8:30 AM", "GUZMAN  DE NAVIDAD, FANNY PATRICIA IDIOMA EXTRANJERO", "LEÓN SILVA, YOLANDA ESTEFANIA FRANCÉS", "RIVERA ROMERO, SANDRA MARLENE CIENCIAS NATURALES", "ZELAYA PÉREZ, ALISSON BERENICE MATEMÁTICA", "MÉNDEZ TEJADA, ANA CECILIA LENGUAJE Y LITERATURA"],
            ["8:30 AM - 8:45 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["8:45 AM - 9:30 AM", "GUZMAN  DE NAVIDAD, FANNY PATRICIA IDIOMA EXTRANJERO", "LEÓN SILVA, YOLANDA ESTEFANIA FRANCÉS", "ZELAYA PÉREZ, ALISSON BERENICE MATEMÁTICA", "RIVERA ROMERO, SANDRA MARLENE CIENCIAS NATURALES", "MÉNDEZ TEJADA, ANA CECILIA LENGUAJE Y LITERATURA"],
            ["9:30 AM - 10:15 AM", "GUZMAN  DE NAVIDAD, FANNY PATRICIA IDIOMA EXTRANJERO", "", "ZELAYA PÉREZ, ALISSON BERENICE MATEMÁTICA", "RIVERA ROMERO, SANDRA MARLENE CIENCIAS NATURALES", "MÉNDEZ TEJADA, ANA CECILIA LENGUAJE Y LITERATURA"],
            ["10:15 AM - 10:30 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["10:30 AM - 11:15 PM", "RIVERA ROMERO, SANDRA MARLENE CIENCIAS NATURALES", "ZELAYA PÉREZ, ALISSON BERENICE MATEMÁTICA", "ANAYA RIVERA, ROXANA MARGARITA ESTUDIOS SOCIALES Y CÍVICA", "MÉNDEZ TEJADA, ANA CECILIA LENGUAJE Y LITERATURA", "ANAYA RIVERA, ROXANA MARGARITA ESTUDIOS SOCIALES Y CÍVICA"],
            ["11:15 PM - 12:00 PM", "RIVERA ROMERO, SANDRA MARLENE CIENCIAS NATURALES", "ZELAYA PÉREZ, ALISSON BERENICE MATEMÁTICA", "ANAYA RIVERA, ROXANA MARGARITA ESTUDIOS SOCIALES Y CÍVICA", "", "ANAYA RIVERA, ROXANA MARGARITA ESTUDIOS SOCIALES Y CÍVICA"],
            ["12:00 PM - 1:00 PM",  "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["1:00 PM - 1:45 PM", "GÓMEZ SERRANO, TELMA MARITZA ORIENTACIÓN PARA LA VIDA", "RIVAS MENDOZA, JOSÉ SAÚL CHL (PANADERÍA Y PASTELERÍA)", "MELARA ESCAMILLA, RICARDO ERNESTO INFORMÁTICA", "SARAVIA  DE YUDICE, EVELYN YANETH SEMINARIOS", "RIVAS MENDOZA, JOSÉ SAÚL CHL (PANADERÍA Y PASTELERÍA)"],
            ["1:45 PM - 2:30 PM", "GÓMEZ SERRANO, TELMA MARITZA ORIENTACIÓN PARA LA VIDA", "RIVAS MENDOZA, JOSÉ SAÚL CHL (PANADERÍA Y PASTELERÍA)", "MELARA ESCAMILLA, RICARDO ERNESTO INFORMÁTICA", "SARAVIA  DE YUDICE, EVELYN YANETH SEMINARIOS", "RIVAS MENDOZA, JOSÉ SAÚL CHL (PANADERÍA Y PASTELERÍA)"],
            ["2:30 PM - 2:45 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["2:45 PM - 3:30 PM", "GÓMEZ SERRANO, TELMA MARITZA ORIENTACIÓN PARA LA VIDA", "SANTANA  LÓPEZ, ANA SELMA GEORGINA CHL (BARTENDER)", "MELARA ESCAMILLA, RICARDO ERNESTO INFORMÁTICA", "SARAVIA  DE YUDICE, EVELYN YANETH SEMINARIOS", "ESPINOZA RAMOS, RICARDO ADOLFO EDUCACIÓN FÍSICA"],
            ["3:30 PM - 4:15 PM", "", "SANTANA  LÓPEZ, ANA SELMA GEORGINA CHL (BARTENDER)", "", "", "ESPINOZA RAMOS, RICARDO ADOLFO EDUCACIÓN FÍSICA"],
            ["4:15 PM - 4:30 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["4:30 PM - 5:15 PM", "", "", "", "", ""],
            ["5:15 PM - 6:00 PM", "", "", "", "", ""],

        ],

        "2-5": [
            ["7:00 AM - 7:45 AM", "ANAYA RIVERA, ROXANA MARGARITA SEMINARIOS", "MÉNDEZ TEJADA, ANA CECILIA LENGUAJE Y LITERATURA", "", "GARCÍA NAVARRO, CARLOS HUMBERTO CIENCIAS NATURALES", "LEÓN SILVA, YOLANDA ESTEFANIA FRANCÉS"],
            ["7:45 AM - 8:30 AM", "ANAYA RIVERA, ROXANA MARGARITA SEMINARIOS", "MÉNDEZ TEJADA, ANA CECILIA LENGUAJE Y LITERATURA", "", "GARCÍA NAVARRO, CARLOS HUMBERTO CIENCIAS NATURALES", "LEÓN SILVA, YOLANDA ESTEFANIA FRANCÉS"],
            ["8:30 AM - 8:45 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["8:45 AM - 9:30 AM", "GARCÍA NAVARRO, CARLOS HUMBERTO CIENCIAS NATURALES", "ANAYA RIVERA, ROXANA MARGARITA SEMINARIOS", "", "ANAYA RIVERA, ROXANA MARGARITA ESTUDIOS SOCIALES Y CÍVICA", "LEÓN SILVA, YOLANDA ESTEFANIA FRANCÉS"],
            ["9:30 AM - 10:15 AM", "GARCÍA NAVARRO, CARLOS HUMBERTO CIENCIAS NATURALES", "ANAYA RIVERA, ROXANA MARGARITA SEMINARIOS", "", "MELARA ESCAMILLA, RICARDO ERNESTO INFORMÁTICA", "MÉNDEZ TEJADA, ANA CECILIA LENGUAJE Y LITERATURA"],
            ["10:15 AM - 10:30 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["10:30 AM - 11:15 PM", "MÉNDEZ TEJADA, ANA CECILIA LENGUAJE Y LITERATURA", "GUZMAN  DE NAVIDAD, FANNY PATRICIA IDIOMA EXTRANJERO", "", "MELARA ESCAMILLA, RICARDO ERNESTO INFORMÁTICA", "GARCÍA NAVARRO, CARLOS HUMBERTO CIENCIAS NATURALES"],
            ["11:15 PM - 12:00 PM", "MÉNDEZ TEJADA, ANA CECILIA LENGUAJE Y LITERATURA", "GUZMAN  DE NAVIDAD, FANNY PATRICIA IDIOMA EXTRANJERO", "", "MELARA ESCAMILLA, RICARDO ERNESTO INFORMÁTICA", "GARCÍA NAVARRO, CARLOS HUMBERTO CIENCIAS NATURALES"],
            ["12:00 PM - 1:00 PM",  "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["1:00 PM - 1:45 PM", "PREZA DÍAZ, ROBERTO CARLOS MATEMÁTICA", "ANAYA RIVERA, ROXANA MARGARITA ESTUDIOS SOCIALES Y CÍVICA", "ANAYA RIVERA, ROXANA MARGARITA ESTUDIOS SOCIALES Y CÍVICA", "SANTANA  LÓPEZ, ANA SELMA GEORGINA CHL (PANADERÍA Y PASTELERÍA)", "GÓMEZ SERRANO, TELMA MARITZA ORIENTACIÓN PARA LA VIDA"],
            ["1:45 PM - 2:30 PM", "PREZA DÍAZ, ROBERTO CARLOS MATEMÁTICA", "ANAYA RIVERA, ROXANA MARGARITA ESTUDIOS SOCIALES Y CÍVICA", "ANAYA RIVERA, ROXANA MARGARITA ESTUDIOS SOCIALES Y CÍVICA", "SANTANA  LÓPEZ, ANA SELMA GEORGINA CHL (PANADERÍA Y PASTELERÍA)", "GÓMEZ SERRANO, TELMA MARITZA ORIENTACIÓN PARA LA VIDA"],
            ["2:30 PM - 2:45 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["2:45 PM - 3:30 PM", "", "PREZA DÍAZ, ROBERTO CARLOS MATEMÁTICA", "RIVAS MENDOZA, JOSÉ SAÚL CHL (BARTENDER)", "SANTANA  LÓPEZ, ANA SELMA GEORGINA CHL (PANADERÍA Y PASTELERÍA)", "GÓMEZ SERRANO, TELMA MARITZA ORIENTACIÓN PARA LA VIDA"],
            ["3:30 PM - 4:15 PM", "", "PREZA DÍAZ, ROBERTO CARLOS MATEMÁTICA", "RIVAS MENDOZA, JOSÉ SAÚL CHL (BARTENDER)", "SANTANA  LÓPEZ, ANA SELMA GEORGINA CHL (PANADERÍA Y PASTELERÍA)", ""],
            ["4:15 PM - 4:30 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["4:30 PM - 5:15 PM", "", "", "PREZA DÍAZ, ROBERTO CARLOS MATEMÁTICA", "", "ESPINOZA RAMOS, RICARDO ADOLFO EDUCACIÓN FÍSICA"],
            ["5:15 PM - 6:00 PM", "", "", "PREZA DÍAZ, ROBERTO CARLOS MATEMÁTICA", "", "ESPINOZA RAMOS, RICARDO ADOLFO EDUCACIÓN FÍSICA"],
        ],
    }
};

// Variables globales
let añoActual = "primero";
let seccionActual = "1-1";

// Cargar horario al iniciar la página
document.addEventListener('DOMContentLoaded', function() {
    cargarHorario(añoActual, seccionActual);
    configurarBotones();
});

// Configurar event listeners para los botones
function configurarBotones() {
    // Botones de año
    const botonesAño = document.querySelectorAll('.btn-year');
    botonesAño.forEach(boton => {
        boton.addEventListener('click', function() {
            botonesAño.forEach(btn => btn.classList.remove('active'));
            this.classList.add('active');
            
            añoActual = this.getAttribute('data-year');
            
            // Mostrar secciones correspondientes al año (CORREGIDO)
            document.querySelectorAll('.secciones').forEach(seccion => {
                seccion.style.display = 'none';
            });
            document.querySelector(`.secciones.${añoActual}`).style.display = 'flex';
            
            // Reiniciar sección actual y actualizar horario
            const primeraSeccion = document.querySelector(`.secciones.${añoActual} .btn-section`).getAttribute('data-section');
            seccionActual = primeraSeccion;
            
            // Actualizar botones de sección (CORREGIDO)
            document.querySelectorAll('.btn-section').forEach(boton => {
                boton.classList.remove('active');
            });
            document.querySelector(`.btn-section[data-section="${primeraSeccion}"]`).classList.add('active');
            
            // Cargar horario
            cargarHorario(añoActual, seccionActual);
            actualizarTitulo();
        });
    });
    
    // Botones de sección
    const botonesSeccion = document.querySelectorAll('.btn-section');
    botonesSeccion.forEach(boton => {
        boton.addEventListener('click', function() {
            botonesSeccion.forEach(btn => btn.classList.remove('active'));
            this.classList.add('active');
            
            seccionActual = this.getAttribute('data-section');
            cargarHorario(añoActual, seccionActual);
            actualizarTitulo();
        });
    });
}

// Cargar horario en la tabla
function cargarHorario(año, seccion) {
    const tbody = document.querySelector('.tabla-horario tbody');
    tbody.innerHTML = '';
    
    const horarioSeccion = horarios[año][seccion];
    
    if (horarioSeccion && horarioSeccion.length > 0) {
        horarioSeccion.forEach(fila => {
            const tr = document.createElement('tr');
            
            fila.forEach((celda, index) => {
                const td = document.createElement('td');
                td.textContent = celda;
                tr.appendChild(td);
            });
            
            tbody.appendChild(tr);
        });
    } else {
        // Mensaje si no hay horario disponible
        const tr = document.createElement('tr');
        const td = document.createElement('td');
        td.colSpan = 6;
        td.textContent = 'Horario no disponible para esta sección';
        td.style.textAlign = 'center';
        td.style.padding = '20px';
        tr.appendChild(td);
        tbody.appendChild(tr);
    }
}

// Actualizar título del horario
function actualizarTitulo() {
    const titulo = document.getElementById('titulo-seccion');
    const añoTexto = añoActual === 'primero' ? 'Primer Año' : 'Segundo Año';
    titulo.textContent = `${añoTexto} - Sección ${seccionActual}`;
}

