const horarios = {
    "primero": {
        "1-1": [
            ["7:00 AM - 7:45 AM", "MELARA ESCAMILLA, RICARDO ERNESTO MÓDULO", "ARÉVALO ROSALES, JUAN ALBERTO IDIOMA EXTRANJERO", "MARTÍNEZ  DE ELÍAS, CLAUDIA RAQUEL ESTUDIOS SOCIALES Y CÍVICA", "MELARA ESCAMILLA, RICARDO ERNESTO MÓDULO", "MELARA ESCAMILLA, RICARDO ERNESTO MÓDULO"],
            ["7:45 AM - 8:30 AM", "MELARA ESCAMILLA, RICARDO ERNESTO MÓDULO", "ARÉVALO ROSALES, JUAN ALBERTO IDIOMA EXTRANJERO", "MARTÍNEZ  DE ELÍAS, CLAUDIA RAQUEL ESTUDIOS SOCIALES Y CÍVIC", "MELARA ESCAMILLA, RICARDO ERNESTO MÓDULO", "MELARA ESCAMILLA, RICARDO ERNESTO MÓDULO"],
            ["8:30 AM - 8:45 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["8:45 AM - 9:30 AM", "MELARA ESCAMILLA, RICARDO ERNESTO MÓDULO", "ARÉVALO ROSALES, JUAN ALBERTO IDIOMA EXTRANJERO", "MARTÍNEZ  DE ELÍAS, CLAUDIA RAQUEL ESTUDIOS SOCIALES Y CÍVIC", "AGUILAR HENRÍQUEZ, MARÍA ELENA MATEMÁTICA", "AGUILAR HENRÍQUEZ, MARÍA ELENA MATEMÁTICA"],
            ["9:30 AM - 10:15 AM", "MELARA ESCAMILLA, RICARDO ERNESTO MÓDULO", "MELARA ESCAMILLA, RICARDO ERNESTO MÓDULO", "MELARA ESCAMILLA, RICARDO ERNESTO MÓDULO", "AGUILAR HENRÍQUEZ, MARÍA ELENA MATEMÁTICA", "AGUILAR HENRÍQUEZ, MARÍA ELENA MATEMÁTICA"],
            ["10:15 AM - 10:30 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["10:30 AM - 11:15 PM", "AGUILAR HENRÍQUEZ, MARÍA ELENA MATEMÁTICA", "MELARA ESCAMILLA, RICARDO ERNESTO MÓDULO", "MELARA ESCAMILLA, RICARDO ERNESTO MÓDULO", "ARÉVALO ROSALES, JUAN ALBERTO IDIOMA EXTRANJERO", "LINARES MURGA, ANA CONCEPCIÓN SERVICIO SOCIAL ESTUDIANTIL"],
            ["11:15 PM - 12:00 PM", "AGUILAR HENRÍQUEZ, MARÍA ELENA MATEMÁTICA", "MELARA ESCAMILLA, RICARDO ERNESTO MÓDULO", "MELARA ESCAMILLA, RICARDO ERNESTO MÓDULO", "ARÉVALO ROSALES, JUAN ALBERTO IDIOMA EXTRANJERO", "LINARES MURGA, ANA CONCEPCIÓN SERVICIO SOCIAL ESTUDIANTIL"],
            ["12:00 PM - 1:00 PM",  "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["1:00 PM - 1:45 PM", "MOLINA  DE FRANCO, SANDRA SOFIA LENGUAJE Y LITERATURA", "MARTÍNEZ  DE ELÍAS, CLAUDIA RAQUEL ESTUDIOS SOCIALES Y CÍVICA", "LOBO DE OLIVA, MAGNOLIA DEL CARMEN MOD 1.6 DS", "MOLINA  DE FRANCO, SANDRA SOFIA LENGUAJE Y LITERATURA", "MANGANDI RAMOS, CARLOS GIOVANNI CIENCIAS NATURALES"],
            ["1:45 PM - 2:30 PM", "OLINA  DE FRANCO, SANDRA SOFIA LENGUAJE Y LITERATURA", "ARTÍNEZ  DE ELÍAS, CLAUDIA RAQUEL ESTUDIOS SOCIALES Y CÍVICA", "LOBO DE OLIVA, MAGNOLIA DEL CARMEN MOD 1.6 DS", "MOLINA  DE FRANCO, SANDRA SOFIA LENGUAJE Y LITERATURA", "MANGANDI RAMOS, CARLOS GIOVANNI CIENCIAS NATURALES"],
            ["2:30 PM - 2:45 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["2:45 PM - 3:30 PM", "OLINA  DE FRANCO, SANDRA SOFIA LENGUAJE Y LITERATURA", "ESPINOZA RAMOS, RICARDO ADOLFO EDUCACIÓN FÍSICA", "MANGANDI RAMOS, CARLOS GIOVANNI CIENCIAS NATURALES", "MIRANDA CÓRDOVA, JOSÉ  JAVIER INFORMÁTICA", "AQUINO SÁNCHEZ, LORENA LISSETTE MOD 1.7 DS"],
            ["3:30 PM - 4:15 PM", "", "ESPINOZA RAMOS, RICARDO ADOLFO EDUCACIÓN FÍSICA", "MANGANDI RAMOS, CARLOS GIOVANNI CIENCIAS NATURALES", "MIRANDA CÓRDOVA, JOSÉ  JAVIER INFORMÁTICA", "AQUINO SÁNCHEZ, LORENA LISSETTE MOD 1.7 DS"],
            ["4:15 PM - 4:30 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["4:30 PM - 5:15 PM", "", "MANGANDI RAMOS, CARLOS GIOVANNI CIENCIAS NATURALES", "", "", ""],
            ["5:15 PM - 6:00 PM", "", "MANGANDI RAMOS, CARLOS GIOVANNI CIENCIAS NATURALES", "", "", ""],
        ],
        "1-2": [
           ["7:00 AM - 7:45 AM", "AGUILAR HENRÍQUEZ, MARÍA ELENA MATEMÁTICA", "MELARA ESCAMILLA, RICARDO ERNESTO MÓDULO", "MELARA ESCAMILLA, RICARDO ERNESTO MÓDULO", "AQUINO SÁNCHEZ, LORENA LISSETTE MOD 1.7 DS", "AGUILAR HENRÍQUEZ, MARÍA ELENA MATEMÁTICA"],
            ["7:45 AM - 8:30 AM", "AGUILAR HENRÍQUEZ, MARÍA ELENA MATEMÁTICA", "MELARA ESCAMILLA, RICARDO ERNESTO MÓDULO", "MELARA ESCAMILLA, RICARDO ERNESTO MÓDULO", "AQUINO SÁNCHEZ, LORENA LISSETTE MOD 1.7 DS", "AGUILAR HENRÍQUEZ, MARÍA ELENA MATEMÁTICA"],
            ["8:30 AM - 8:45 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["8:45 AM - 9:30 AM", "ARÉVALO ROSALES, JUAN ALBERTO IDIOMA EXTRANJERO", "AGUILAR HENRÍQUEZ, MARÍA ELENA MATEMÁTICA", "MELARA ESCAMILLA, RICARDO ERNESTO MÓDULO", "ARÉVALO ROSALES, JUAN ALBERTO IDIOMA EXTRANJERO", "MELARA ESCAMILLA,RICARDO ERNESTO MÓDULO"],
            ["9:30 AM - 10:15 AM", "ARÉVALO ROSALES, JUAN ALBERTO IDIOMA EXTRANJERO", "AGUILAR HENRÍQUEZ, MARÍA ELENA MATEMÁTICA", "MARTÍNEZ  DE ELÍAS, CLAUDIA RAQUEL ESTUDIOS SOCIALES Y CÍVICA", "", "MELARA ESCAMILLA,RICARDO ERNESTO MÓDULO"],
            ["10:15 AM - 10:30 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["10:30 AM - 11:15 PM", "MELARA ESCAMILLA, RICARDO ERNESTO MÓDULO", "ARÉVALO ROSALES, JUAN ALBERTO IDIOMA EXTRANJERO", "MARTÍNEZ  DE ELÍAS, CLAUDIA RAQUEL ESTUDIOS SOCIALES Y CÍVICA", "LINARES MURGA, ANA CONCEPCIÓN SERVICIO SOCIAL ESTUDIANTIL", "MELARA ESCAMILLA,RICARDO ERNESTO MÓDULO"],
            ["11:15 PM - 12:00 PM", "MELARA ESCAMILLA, RICARDO ERNESTO MÓDULO", "ARÉVALO ROSALES, JUAN ALBERTO IDIOMA EXTRANJERO", "MARTÍNEZ  DE ELÍAS, CLAUDIA RAQUEL ESTUDIOS SOCIALES Y CÍVICA", "LINARES MURGA, ANA CONCEPCIÓN SERVICIO SOCIAL ESTUDIANTIL", "MELARA ESCAMILLA,RICARDO ERNESTO MÓDULO"],
            ["12:00 PM - 1:00 PM",  "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["1:00 PM - 1:45 PM", "LOBO DE OLIVA, MAGNOLIA DEL CARMEN MOD 1.6 DS", "MOLINA  DE FRANCO, SANDRA SOFIA LENGUAJE Y LITERATURA", "MANGANDI RAMOS, CARLOS GIOVANNI CIENCIAS NATURALES", "MARTÍNEZ  DE ELÍAS, CLAUDIA RAQUEL ESTUDIOS SOCIALES Y CÍVICA", ""],
            ["1:45 PM - 2:30 PM", "LOBO DE OLIVA, MAGNOLIA DEL CARMEN MOD 1.6 DS", "MOLINA  DE FRANCO, SANDRA SOFIA LENGUAJE Y LITERATURA", "MANGANDI RAMOS, CARLOS GIOVANNI CIENCIAS NATURALES", "MARTÍNEZ  DE ELÍAS, CLAUDIA RAQUEL ESTUDIOS SOCIALES Y CÍVICA", ""],
            ["2:30 PM - 2:45 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["2:45 PM - 3:30 PM", "MANGANDI RAMOS, CARLOS GIOVANNI CIENCIAS NATURALES", "MANGANDI RAMOS, CARLOS GIOVANNI CIENCIAS NATURALES", "ESPINOZA RAMOS, RICARDO  ADOLFO EDUCACIÓN FÍSICA", "MOLINA  DE FRANCO, SANDRA SOFIA LENGUAJE Y LITERATURA", ""],
            ["3:30 PM - 4:15 PM", "MANGANDI RAMOS, CARLOS GIOVANNI CIENCIAS NATURALES", "MANGANDI RAMOS, CARLOS GIOVANNI CIENCIAS NATURALES", "ESPINOZA RAMOS, RICARDO  ADOLFO EDUCACIÓN FÍSICA", "", ""],
            ["4:15 PM - 4:30 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["4:30 PM - 5:15 PM", "MOLINA  DE FRANCO,SANDRA SOFIA LENGUAJE Y LITERATURA", "", "MIRANDA CÓRDOVA, JOSÉ  JAVIER INFORMÁTICA", "MELARA ESCAMILLA,RICARDO ERNESTO MÓDULO", ""],
            ["5:15 PM - 6:00 PM", "MOLINA  DE FRANCO,SANDRA SOFIA LENGUAJE Y LITERATURA", "", "MIRANDA CÓRDOVA, JOSÉ  JAVIER INFORMÁTICA", "MELARA ESCAMILLA,RICARDO ERNESTO MÓDULO", ""],
        ],
        "1-3":[
            ["7:00 AM - 7:45 AM", "REYES GALÁN, EDWIN ELISEO MÓDULO", "AGUILAR HENRÍQUEZ, MARÍA ELENA MATEMÁTICA", "REYES GALÁN, EDWIN ELISEO MÓDULO", "AGUILAR HENRÍQUEZ, MARÍA ELENA MATEMÁTICA", "MARTÍNEZ  DE ELÍAS, CLAUDIA RAQUEL ESTUDIOS SOCIALES Y CÍVICA"],
            ["7:45 AM - 8:30 AM", "REYES GALÁN, EDWIN ELISEO MÓDULO", "AGUILAR HENRÍQUEZ, MARÍA ELENA MATEMÁTICA", "REYES GALÁN, EDWIN ELISEO MÓDULO", "AGUILAR HENRÍQUEZ, MARÍA ELENA MATEMÁTICA", "MARTÍNEZ  DE ELÍAS, CLAUDIA RAQUEL ESTUDIOS SOCIALES Y CÍVICA"],
            ["8:30 AM - 8:45 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["8:45 AM - 9:30 AM", "LINARES MURGA, ANA CONCEPCIÓN SERVICIO SOCIAL ESTUDIANTIL", "REYES GALÁN, EDWIN ELISEO MÓDULO", "ARÉVALO ROSALES, JUAN ALBERTO IDIOMA EXTRANJERO", "REYES GALÁN, EDWIN ELISEO MÓDULO", "ARÉVALO ROSALES, JUAN ALBERTO IDIOMA EXTRANJERO"],
            ["9:30 AM - 10:15 AM", "LINARES MURGA, ANA CONCEPCIÓN SERVICIO SOCIAL ESTUDIANTIL", "REYES GALÁN, EDWIN ELISEO MÓDULO", "ARÉVALO ROSALES, JUAN ALBERTO IDIOMA EXTRANJERO", "REYES GALÁN, EDWIN ELISEO MÓDULO", "ARÉVALO ROSALES, JUAN ALBERTO IDIOMA EXTRANJERO"],
            ["10:15 AM - 10:30 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["10:30 AM - 11:15 PM", "ARÉVALO ROSALES, JUAN ALBERTO IDIOMA EXTRANJERO", "REYES GALÁN, EDWIN ELISEO MÓDULO", "AGUILAR HENRÍQUEZ, MARÍA ELENA MATEMÁTICA", "REYES GALÁN, EDWIN ELISEO MÓDULO", "REYES GALÁN, EDWIN ELISEO MÓDULO"],
            ["11:15 PM - 12:00 PM", "", "REYES GALÁN, EDWIN ELISEO MÓDULO", "AGUILAR HENRÍQUEZ, MARÍA ELENA MATEMÁTICA", "REYES GALÁN, EDWIN ELISEO MÓDULO", "REYES GALÁN, EDWIN ELISEO MÓDULO"],
            ["12:00 PM - 1:00 PM",  "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["1:00 PM - 1:45 PM", "MIRANDA CÓRDOVA, JOSÉ  JAVIER INFORMÁTICA", "MANGANDI RAMOS, CARLOS GIOVANNI CIENCIAS NATURALES", "ESPINOZA RAMOS, RICARDO ADOLFO EDUCACIÓN FÍSICA", "MANGANDI RAMOS, CARLOS GIOVANNI CIENCIAS NATURALES", "MOLINA  DE FRANCO, SANDRA SOFIA LENGUAJE Y LITERATURA"],
            ["1:45 PM - 2:30 PM", "MIRANDA CÓRDOVA, JOSÉ  JAVIER INFORMÁTICA", "MANGANDI RAMOS, CARLOS GIOVANNI CIENCIAS NATURALES", "ESPINOZA RAMOS, RICARDO ADOLFO EDUCACIÓN FÍSICA", "MANGANDI RAMOS, CARLOS GIOVANNI CIENCIAS NATURALES", "MOLINA  DE FRANCO, SANDRA SOFIA LENGUAJE Y LITERATURA"],
            ["2:30 PM - 2:45 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["2:45 PM - 3:30 PM", "AQUINO SÁNCHEZ, LORENA LISSETTE MOD 1.7 DS", "MARTÍNEZ  DE ELÍAS, CLAUDIA RAQUEL ESTUDIOS SOCIALES Y CÍVICA", "MOLINA  DE FRANCO, SANDRA SOFIA LENGUAJE Y LITERATURA", "LOBO DE OLIVA, MAGNOLIA DEL CARMEN MOD 1.6 DS", "MOLINA  DE FRANCO, SANDRA SOFIA LENGUAJE Y LITERATURA"],
            ["3:30 PM - 4:15 PM", "AQUINO SÁNCHEZ, LORENA LISSETTE MOD 1.7 DS", "MARTÍNEZ  DE ELÍAS, CLAUDIA RAQUEL ESTUDIOS SOCIALES Y CÍVICA", "MOLINA  DE FRANCO, SANDRA SOFIA LENGUAJE Y LITERATURA", "LOBO DE OLIVA, MAGNOLIA DEL CARMEN MOD 1.6 DS", ""],
            ["4:15 PM - 4:30 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["4:30 PM - 5:15 PM", "MANGANDI RAMOS, CARLOS,GIOVANNI CIENCIAS NATURALES", "MARTÍNEZ  DE ELÍAS, CLAUDIA RAQUEL ESTUDIOS SOCIALES Y CÍVICA", "", "", ""],
            ["5:15 PM - 6:00 PM", "MANGANDI RAMOS, CARLOS,GIOVANNI CIENCIAS NATURALES", "", "", "", ""],
        ],
        "1-4":[
             ["7:00 AM - 7:45 AM", "ARÉVALO ROSALES, JUAN ALBERTO IDIOMA EXTRANJERO", "REYES GALÁN, EDWIN ELISEO MÓDULO", "AGUILAR HENRÍQUEZ, MARÍA ELENA MATEMÁTICA", "REYES GALÁN, EDWIN ELISEO MÓDULO", "REYES GALÁN, EDWIN ELISEO MÓDULO"],
            ["7:45 AM - 8:30 AM", "ARÉVALO ROSALES, JUAN ALBERTO IDIOMA EXTRANJERO", "REYES GALÁN, EDWIN ELISEO MÓDULO", "AGUILAR HENRÍQUEZ, MARÍA ELENA MATEMÁTICA", "REYES GALÁN, EDWIN ELISEO MÓDULO", "REYES GALÁN, EDWIN ELISEO MÓDULO"],
            ["8:30 AM - 8:45 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["8:45 AM - 9:30 AM", "AGUILAR HENRÍQUEZ, MARÍA ELENA MATEMÁTICA", "MARTÍNEZ  DE ELÍAS, CLAUDIA RAQUEL ESTUDIOS SOCIALES Y CÍVICA", "REYES GALÁN, EDWIN ELISEO MÓDULO", "", "REYES GALÁN, EDWIN ELISEO MÓDULO"],
            ["9:30 AM - 10:15 AM", "AGUILAR HENRÍQUEZ, MARÍA ELENA MATEMÁTICA", "MARTÍNEZ  DE ELÍAS, CLAUDIA RAQUEL ESTUDIOS SOCIALES Y CÍVICA", "REYES GALÁN, EDWIN ELISEO MÓDULO", "ARÉVALO ROSALES, JUAN ALBERTO IDIOMA EXTRANJERO", "REYES GALÁN, EDWIN ELISEO MÓDULO"],
            ["10:15 AM - 10:30 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["10:30 AM - 11:15 PM", "REYES GALÁN, EDWIN ELISEO MÓDULO", "LINARES MURGA, ANA CONCEPCIÓN SERVICIO SOCIAL ESTUDIANTIL", "REYES GALÁN, EDWIN ELISEO MÓDULO", "AGUILAR HENRÍQUEZ, MARÍA ELENA MATEMÁTICA", "ARÉVALO ROSALES, JUAN ALBERTO IDIOMA EXTRANJERO"],
            ["11:15 PM - 12:00 PM", "REYES GALÁN, EDWIN ELISEO MÓDULO", "LINARES MURGA, ANA CONCEPCIÓN SERVICIO SOCIAL ESTUDIANTIL", "REYES GALÁN, EDWIN ELISEO MÓDULO", "AGUILAR HENRÍQUEZ, MARÍA ELENA MATEMÁTICA", "ARÉVALO ROSALES, JUAN ALBERTO IDIOMA EXTRANJERO"],
            ["12:00 PM - 1:00 PM",  "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["1:00 PM - 1:45 PM", "MANGANDI RAMOS, CARLOSGIOVANNI CIENCIAS NATURALES", "", "MOLINA  DE FRANCO, SANDRA SOFIA LENGUAJE Y LITERATURA", "ESPINOZA RAMOS, RICARDO ADOLFO EDUCACIÓN FÍSICA", "AQUINO SÁNCHEZ, LORENA LISSETTE MOD 1.7 DS"],
            ["1:45 PM - 2:30 PM", "MANGANDI RAMOS, CARLOSGIOVANNI CIENCIAS NATURALES", "", "MOLINA  DE FRANCO, SANDRA SOFIA LENGUAJE Y LITERATURA", "ESPINOZA RAMOS, RICARDO ADOLFO EDUCACIÓN FÍSICA", "AQUINO SÁNCHEZ, LORENA LISSETTE MOD 1.7 DS"],
            ["2:30 PM - 2:45 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["2:45 PM - 3:30 PM", "MIRANDA CÓRDOVA, JOSÉ  JAVIER INFORMÁTICA", "", "MARTÍNEZ  DE ELÍAS, CLAUDIA RAQUEL ESTUDIOS SOCIALES Y CÍVICA", "MANGANDI RAMOS, CARLOS  GIOVANNI CIENCIAS NATURALES", "MANGANDI RAMOS, CARLOS GIOVANNI CIENCIAS NATURALES"],
            ["3:30 PM - 4:15 PM", "MIRANDA CÓRDOVA, JOSÉ  JAVIER INFORMÁTICA", "", "MARTÍNEZ  DE ELÍAS, CLAUDIA RAQUEL ESTUDIOS SOCIALES Y CÍVICA", "MANGANDI RAMOS, CARLOS  GIOVANNI CIENCIAS NATURALES", "MANGANDI RAMOS, CARLOS GIOVANNI CIENCIAS NATURALES"],
            ["4:15 PM - 4:30 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["4:30 PM - 5:15 PM", "LOBO DE OLIVA, MAGNOLIA DEL CARMEN MOD 1.6 DS", "", "MARTÍNEZ  DE ELÍAS, CLAUDIA RAQUEL ESTUDIOS SOCIALES Y CÍVICA", "MOLINA  DE FRANCO, SANDRA SOFIA LENGUAJE Y LITERATURA", "MOLINA  DE FRANCO, SANDRA SOFIA LENGUAJE Y LITERATURA"],
            ["5:15 PM - 6:00 PM", "LOBO DE OLIVA, MAGNOLIA DEL CARMEN MOD 1.6 DS", "", "", "", "MOLINA  DE FRANCO, SANDRA SOFIA LENGUAJE Y LITERATURA"],
        ],
        
    },
    "segundo": {
        "2-1": [
             ["7:00 AM - 7:45 AM", "AQUINO SÁNCHEZ, LORENA LISSETTE MOD 2.7 DS", "RAMOS ALBERTO, JOSÉ  LUIS MATEMÁTICA", "MENJIVAR LARIOS, BLANCA ARGENTINA CIENCIAS NATURALES", "DÍAZ CALLEJAS, DAVID MAURICIO MÓDULO", "TOBAR  DE CÓRDOVA, CLAUDIA PATRICIA ORIENTACIÓN PARA LA VIDA"],
            ["7:45 AM - 8:30 AM", "AQUINO SÁNCHEZ, LORENA LISSETTE MOD 2.7 DS", "RAMOS ALBERTO, JOSÉ  LUIS MATEMÁTICA", "MENJIVAR LARIOS, BLANCA ARGENTINA CIENCIAS NATURALES", "DÍAZ CALLEJAS, DAVID MAURICIO MÓDULO", "TOBAR  DE CÓRDOVA, CLAUDIA PATRICIA ORIENTACIÓN PARA LA VIDA"],
            ["8:30 AM - 8:45 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["8:45 AM - 9:30 AM", "DÍAZ CALLEJAS, DAVID MAURICIO MÓDULO", "DÍAZ CALLEJAS, DAVID MAURICIO MÓDULO", "DÍAZ CALLEJAS, DAVID MAURICIO MÓDULO", "DÍAZ CALLEJAS, DAVID MAURICIO MÓDULO", "RAMOS ALBERTO, JOSÉ LUIS MATEMÁTICA"],
            ["9:30 AM - 10:15 AM", "DÍAZ CALLEJAS, DAVID MAURICIO MÓDULO", "DÍAZ CALLEJAS, DAVID MAURICIO MÓDULO", "DÍAZ CALLEJAS, DAVID MAURICIO MÓDULO", "DÍAZ CALLEJAS, DAVID MAURICIO MÓDULO", "RAMOS ALBERTO, JOSÉ LUIS MATEMÁTICA"],
            ["10:15 AM - 10:30 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["10:30 AM - 11:15 PM", "DÍAZ CALLEJAS, DAVID MAURICIO MÓDULO", "MENJIVAR LARIOS, BLANCA ARGENTINA CIENCIAS NATURALES", "DÍAZ CALLEJAS, DAVID MAURICIO MÓDULO", "RAMOS ALBERTO, JOSÉ  LUIS MATEMÁTICA", "MENJIVAR LARIOS, BLANCA ARGENTINA CIENCIAS NATURALES"],
            ["11:15 PM - 12:00 PM", "DÍAZ CALLEJAS, DAVID MAURICIO MÓDULO", "MENJIVAR LARIOS, BLANCA ARGENTINA CIENCIAS NATURALES", "DÍAZ CALLEJAS, DAVID MAURICIO MÓDULO", "RAMOS ALBERTO, JOSÉ  LUIS MATEMÁTICA", "MENJIVAR LARIOS, BLANCA ARGENTINA CIENCIAS NATURALES"],
            ["12:00 PM - 1:00 PM",  "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["1:00 PM - 1:45 PM", "POLIO CORTEZ, GERBER ALEXANDER IDIOMA EXTRANJERO", "POLIO CORTEZ, GERBER ALEXANDER IDIOMA EXTRANJERO", "MORAN LORENZANA, JOSÉ FRANCISCO LENGUAJE Y LITERATURA", "BARRERA ORTEGA, MARIA ELENA ESTUDIOS SOCIALES Y CÍVICA", "MORAN LORENZANA, JOSÉ FRANCISCO LENGUAJE Y LITERATURA"],
            ["1:45 PM - 2:30 PM", "POLIO CORTEZ, GERBER ALEXANDER IDIOMA EXTRANJERO", "POLIO CORTEZ, GERBER ALEXANDER IDIOMA EXTRANJERO", "MORAN LORENZANA, JOSÉ FRANCISCO LENGUAJE Y LITERATURA", "BARRERA ORTEGA, MARIA ELENA ESTUDIOS SOCIALES Y CÍVICA", "MORAN LORENZANA, JOSÉ FRANCISCO LENGUAJE Y LITERATURA"],
            ["2:30 PM - 2:45 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["2:45 PM - 3:30 PM", "POLIO CORTEZ, GERBER ALEXANDER IDIOMA EXTRANJERO", "LOBO DE OLIVA, MAGNOLIA DEL CARMEN MOD 2.6 DS", "MORAN LORENZANA, JOSÉ FRANCISCO LENGUAJE Y LITERATURA", "ESPINOZA RAMOS, RICARDO ADOLFO EDUCACIÓN FÍSICA", ""],
            ["3:30 PM - 4:15 PM", "", "LOBO DE OLIVA, MAGNOLIA DEL CARMEN MOD 2.6 DS", "MORAN LORENZANA, JOSÉ FRANCISCO LENGUAJE Y LITERATURA", "ESPINOZA RAMOS, RICARDO ADOLFO EDUCACIÓN FÍSICA", ""],
            ["4:15 PM - 4:30 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["4:30 PM - 5:15 PM", "", "", "BARRERA ORTEGA, MARIA ELENA ESTUDIOS SOCIALES Y CÍVICA", "", ""],
            ["5:15 PM - 6:00 PM", "", "", "BARRERA ORTEGA, MARIA ELENA ESTUDIOS SOCIALES Y CÍVICA", "", ""],
        ],
        "2-2": [
             ["7:00 AM - 7:45 AM", "", "", "", "", ""],
            ["7:45 AM - 8:30 AM", "", "", "", "", ""],
            ["8:30 AM - 8:45 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["8:45 AM - 9:30 AM", "", "", "", "", ""],
            ["9:30 AM - 10:15 AM", "", "", "", "", ""],
            ["10:15 AM - 10:30 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["10:30 AM - 11:15 PM", "", "", "", "", ""],
            ["11:15 PM - 12:00 PM", "", "", "", "", ""],
            ["12:00 PM - 1:00 PM",  "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["1:00 PM - 1:45 PM", "", "", "", "", ""],
            ["1:45 PM - 2:30 PM", "", "", "", "", ""],
            ["2:30 PM - 2:45 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["2:45 PM - 3:30 PM", "", "", "", "", ""],
            ["3:30 PM - 4:15 PM", "", "", "", "", ""],
            ["4:15 PM - 4:30 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["4:30 PM - 5:15 PM", "", "", "", "", ""],
            ["5:15 PM - 6:00 PM", "", "", "", "", ""],
        ],
        "2-3":[
             ["7:00 AM - 7:45 AM", "TOBAR  DE CÓRDOVA, CLAUDIA PATRICIA ORIENTACIÓN PARA LA VIDA", "MENJIVAR LARIOS, BLANCA ARGENTINA CIENCIAS NATURALES", "RAMOS ALBERTO, JOSÉ LUIS MATEMÁTICA", "RAMOS ALBERTO, JOSÉ  LUIS MATEMÁTICA", ""],
            ["7:45 AM - 8:30 AM", "TOBAR  DE CÓRDOVA, CLAUDIA PATRICIA ORIENTACIÓN PARA LA VIDA", "MENJIVAR LARIOS, BLANCA ARGENTINA CIENCIAS NATURALES", "RAMOS ALBERTO, JOSÉ LUIS MATEMÁTICA", "RAMOS ALBERTO, JOSÉ  LUIS MATEMÁTICA", ""],
            ["8:30 AM - 8:45 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["8:45 AM - 9:30 AM", "RAMOS ALBERTO, JOSÉ  LUIS MATEMÁTICA", "POLIO CORTEZ, GERBER ALEXANDER IDIOMA EXTRANJERO", "AQUINO SÁNCHEZ, LORENA LISSETTE MOD 2.7 DS", "MENJIVAR LARIOS, BLANCA ARGENTINA CIENCIAS NATURALES", ""],
            ["9:30 AM - 10:15 AM", "RAMOS ALBERTO, JOSÉ  LUIS MATEMÁTICA", "POLIO CORTEZ, GERBER ALEXANDER IDIOMA EXTRANJERO", "AQUINO SÁNCHEZ, LORENA LISSETTE MOD 2.7 DS", "MENJIVAR LARIOS, BLANCA ARGENTINA CIENCIAS NATURALES", ""],
            ["10:15 AM - 10:30 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["10:30 AM - 11:15 PM", "MENJIVAR LARIOS, BLANCA ARGENTINA CIENCIAS NATURALES", "CABEZAS VÁSQUEZ, JOSÉ MAURICIO EDUCACIÓN FÍSICA", "", "", ""],
            ["11:15 PM - 12:00 PM", "MENJIVAR LARIOS, BLANCA ARGENTINA CIENCIAS NATURALES", "CABEZAS VÁSQUEZ, JOSÉ MAURICIO EDUCACIÓN FÍSICA", "", "", ""],
            ["12:00 PM - 1:00 PM",  "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["1:00 PM - 1:45 PM", "CHACON BRITO, EDWIN FRANCISCO MÓDULO", "BARRERA ORTEGA, MARIA ELENA ESTUDIOS SOCIALES Y CÍVICA", "CHACON BRITO, EDWIN FRANCISCO MÓDULO", "LOBO DE OLIVA, MAGNOLIA DEL CARMEN MOD 2.6 DS", "POLIO CORTEZ, GERBER ALEXANDER IDIOMA EXTRANJERO"],
            ["1:45 PM - 2:30 PM", "CHACON BRITO, EDWIN FRANCISCO MÓDULO", "BARRERA ORTEGA, MARIA ELENA ESTUDIOS SOCIALES Y CÍVICA", "CHACON BRITO, EDWIN FRANCISCO MÓDULO", "LOBO DE OLIVA, MAGNOLIA DEL CARMEN MOD 2.6 DS", "POLIO CORTEZ, GERBER ALEXANDER IDIOMA EXTRANJERO"],
            ["2:30 PM - 2:45 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["2:45 PM - 3:30 PM", "CHACON BRITO, EDWIN FRANCISCO MÓDULO", "BARRERA ORTEGA, MARIA ELENA ESTUDIOS SOCIALES Y CÍVICA", "CHACON BRITO, EDWIN FRANCISCO MÓDULO", "BARRERA ORTEGA, MARIA ELENA ESTUDIOS SOCIALES Y CÍVICA", "CHACON BRITO, EDWIN FRANCISCO MÓDULO"],
            ["3:30 PM - 4:15 PM", "CHACON BRITO, EDWIN FRANCISCO MÓDULO", "MORAN LORENZANA, JOSÉ FRANCISCO LENGUAJE Y LITERATURA", "CHACON BRITO, EDWIN FRANCISCO MÓDULO", "BARRERA ORTEGA, MARIA ELENA ESTUDIOS SOCIALES Y CÍVICA", "CHACON BRITO, EDWIN FRANCISCO MÓDULO"],
            ["4:15 PM - 4:30 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["4:30 PM - 5:15 PM", "MORAN LORENZANA, JOSÉ FRANCISCO LENGUAJE Y LITERATURA", "MORAN LORENZANA, JOSÉ FRANCISCO LENGUAJE Y LITERATURA", "", "CHACON BRITO, EDWIN FRANCISCO MÓDULO", "CHACON BRITO, EDWIN FRANCISCO MÓDULO"],
            ["5:15 PM - 6:00 PM", "MORAN LORENZANA, JOSÉ FRANCISCO LENGUAJE Y LITERATURA", "MORAN LORENZANA, JOSÉ FRANCISCO LENGUAJE Y LITERATURA", "", "CHACON BRITO, EDWIN FRANCISCO MÓDULO", "CHACON BRITO, EDWIN FRANCISCO MÓDULO"],
        ],
        "2-4":[
             ["7:00 AM - 7:45 AM", "MENJIVAR LARIOS, BLANCA ARGENTINA CIENCIAS NATURALES", "TOBAR  DE CÓRDOVA, CLAUDIA PATRICIA ORIENTACIÓN PARA LA VIDA", "AQUINO SÁNCHEZ, LORENA LISSETTE MOD 2.7 DS", "", "RAMOS ALBERTO, JOSÉ  LUIS MATEMÁTICA"],
            ["7:45 AM - 8:30 AM", "MENJIVAR LARIOS, BLANCA ARGENTINA CIENCIAS NATURALES", "TOBAR  DE CÓRDOVA, CLAUDIA PATRICIA ORIENTACIÓN PARA LA VIDA", "AQUINO SÁNCHEZ, LORENA LISSETTE MOD 2.7 DS", "", "RAMOS ALBERTO, JOSÉ  LUIS MATEMÁTICA"],
            ["8:30 AM - 8:45 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["8:45 AM - 9:30 AM", "POLIO CORTEZ, GERBER ALEXANDER IDIOMA EXTRANJERO", "MENJIVAR LARIOS, BLANCA ARGENTINA CIENCIAS NATURALES", "GRANADOS BLANCO, MARIO DOUGLAS EDUCACIÓN FÍSICA", "", "MENJIVAR LARIOS, BLANCA ARGENTINA CIENCIAS NATURALES"],
            ["9:30 AM - 10:15 AM", "POLIO CORTEZ, GERBER ALEXANDER IDIOMA EXTRANJERO", "MENJIVAR LARIOS, BLANCA ARGENTINA CIENCIAS NATURALES", "GRANADOS BLANCO, MARIO DOUGLAS EDUCACIÓN FÍSICA", "", "MENJIVAR LARIOS, BLANCA ARGENTINA CIENCIAS NATURALES"],
            ["10:15 AM - 10:30 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["10:30 AM - 11:15 PM", "", "RAMOS ALBERTO, JOSÉ  LUIS MATEMÁTICA", "RAMOS ALBERTO, JOSÉ  LUIS MATEMÁTICA", "", ""],
            ["11:15 PM - 12:00 PM", "", "RAMOS ALBERTO, JOSÉ  LUIS MATEMÁTICA", "RAMOS ALBERTO, JOSÉ  LUIS MATEMÁTICA", "", ""],
            ["12:00 PM - 1:00 PM",  "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["1:00 PM - 1:45 PM", "MORAN LORENZANA, JOSÉ FRANCISCO LENGUAJE Y LITERATURA", "CHACON BRITO, EDWIN FRANCISCO MÓDULO", "POLIO CORTEZ, GERBER ALEXANDER IDIOMA EXTRANJERO", "CHACON BRITO, EDWIN FRANCISCO", "CHACON BRITO, EDWIN FRANCISCO MÓDULO"],
            ["1:45 PM - 2:30 PM", "MORAN LORENZANA, JOSÉ FRANCISCO LENGUAJE Y LITERATURA", "CHACON BRITO, EDWIN FRANCISCO MÓDULO", "POLIO CORTEZ, GERBER ALEXANDER IDIOMA EXTRANJERO", "CHACON BRITO, EDWIN FRANCISCO", "CHACON BRITO, EDWIN FRANCISCO MÓDULO"],
            ["2:30 PM - 2:45 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["2:45 PM - 3:30 PM", "LOBO DE OLIVA, MAGNOLIA DEL CARMEN MOD 2.6 DS", "CHACON BRITO, EDWIN FRANCISCO MÓDULO", "POLIO CORTEZ, GERBER ALEXANDER IDIOMA EXTRANJERO", "CHACON BRITO, EDWIN FRANCISCO", "MORAN LORENZANA, JOSÉ FRANCISCO LENGUAJE Y LITERATURA"],
            ["3:30 PM - 4:15 PM", "LOBO DE OLIVA, MAGNOLIA DEL CARMEN MOD 2.6 DS", "CHACON BRITO, EDWIN FRANCISCO MÓDULO", "MORAN LORENZANA, JOSÉ FRANCISCO LENGUAJE Y LITERATURA", "CHACON BRITO, EDWIN FRANCISCO", "MORAN LORENZANA, JOSÉ FRANCISCO LENGUAJE Y LITERATURA"],
            ["4:15 PM - 4:30 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["4:30 PM - 5:15 PM", "CHACON BRITO, EDWIN FRANCISCO MÓDULO", "BARRERA ORTEGA, MARIA ELENA ESTUDIOS SOCIALESY CÍVICA", "CHACON BRITO, EDWIN FRANCISCO", "BARRERA ORTEGA, MARIA ELENA ESTUDIOS SOCIALES Y CÍVICA", "BARRERA ORTEGA, MARIA ELENA ESTUDIOS SOCIALES Y CÍVICA"],
            ["5:15 PM - 6:00 PM", "CHACON BRITO, EDWIN FRANCISCO MÓDULO", "", "CHACON BRITO, EDWIN FRANCISCO", "BARRERA ORTEGA, MARIA ELENA ESTUDIOS SOCIALES Y CÍVICA", "BARRERA ORTEGA, MARIA ELENA ESTUDIOS SOCIALES Y CÍVICA"],
        ],
        
    },
    "tercero":{
        "3-1": [
            ["7:00 AM - 7:45 AM", "", "", "", "", ""],
            ["7:45 AM - 8:30 AM", "", "", "", "", ""],
            ["8:30 AM - 8:45 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["8:45 AM - 9:30 AM", "", "", "", "", ""],
            ["9:30 AM - 10:15 AM", "", "", "", "", ""],
            ["10:15 AM - 10:30 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["10:30 AM - 11:15 PM", "", "", "", "", ""],
            ["11:15 PM - 12:00 PM", "", "", "", "", ""],
            ["12:00 PM - 1:00 PM",  "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["1:00 PM - 1:45 PM", "", "", "", "", ""],
            ["1:45 PM - 2:30 PM", "", "", "", "", ""],
            ["2:30 PM - 2:45 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["2:45 PM - 3:30 PM", "", "", "", "", ""],
            ["3:30 PM - 4:15 PM", "", "", "", "", ""],
            ["4:15 PM - 4:30 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["4:30 PM - 5:15 PM", "", "", "", "", ""],
            ["5:15 PM - 6:00 PM", "", "", "", "", ""],
        ],
        "3-2": [
            ["7:00 AM - 7:45 AM", "", "", "", "", ""],
            ["7:45 AM - 8:30 AM", "", "", "", "", ""],
            ["8:30 AM - 8:45 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["8:45 AM - 9:30 AM", "", "", "", "", ""],
            ["9:30 AM - 10:15 AM", "", "", "", "", ""],
            ["10:15 AM - 10:30 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["10:30 AM - 11:15 PM", "", "", "", "", ""],
            ["11:15 PM - 12:00 PM", "", "", "", "", ""],
            ["12:00 PM - 1:00 PM",  "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["1:00 PM - 1:45 PM", "", "", "", "", ""],
            ["1:45 PM - 2:30 PM", "", "", "", "", ""],
            ["2:30 PM - 2:45 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["2:45 PM - 3:30 PM", "", "", "", "", ""],
            ["3:30 PM - 4:15 PM", "", "", "", "", ""],
            ["4:15 PM - 4:30 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["4:30 PM - 5:15 PM", "", "", "", "", ""],
            ["5:15 PM - 6:00 PM", "", "", "", "", ""],
        ],

    },
    
};

// Variables globales
let añoActual = "primero";
let seccionActual = "1-1";

// Cargar horario al iniciar la página
document.addEventListener('DOMContentLoaded', function() {
    cargarHorario(añoActual, seccionActual);
    configurarBotones();
});

// Configurar event listeners para los botones
function configurarBotones() {
    // Botones de año
    const botonesAño = document.querySelectorAll('.btn-year');
    botonesAño.forEach(boton => {
        boton.addEventListener('click', function() {
            botonesAño.forEach(btn => btn.classList.remove('active'));
            this.classList.add('active');
            
            añoActual = this.getAttribute('data-year');
            
            // Mostrar secciones correspondientes al año (CORREGIDO)
            document.querySelectorAll('.secciones').forEach(seccion => {
                seccion.style.display = 'none';
            });
            document.querySelector(`.secciones.${añoActual}`).style.display = 'flex';
            
            // Reiniciar sección actual y actualizar horario
            const primeraSeccion = document.querySelector(`.secciones.${añoActual} .btn-section`).getAttribute('data-section');
            seccionActual = primeraSeccion;
            
            // Actualizar botones de sección (CORREGIDO)
            document.querySelectorAll('.btn-section').forEach(boton => {
                boton.classList.remove('active');
            });
            document.querySelector(`.btn-section[data-section="${primeraSeccion}"]`).classList.add('active');
            
            // Cargar horario
            cargarHorario(añoActual, seccionActual);
            actualizarTitulo();
        });
    });
    
    // Botones de sección
    const botonesSeccion = document.querySelectorAll('.btn-section');
    botonesSeccion.forEach(boton => {
        boton.addEventListener('click', function() {
            botonesSeccion.forEach(btn => btn.classList.remove('active'));
            this.classList.add('active');
            
            seccionActual = this.getAttribute('data-section');
            cargarHorario(añoActual, seccionActual);
            actualizarTitulo();
        });
    });
}

// Cargar horario en la tabla
function cargarHorario(año, seccion) {
    const tbody = document.querySelector('.tabla-horario tbody');
    tbody.innerHTML = '';
    
    const horarioSeccion = horarios[año][seccion];
    
    if (horarioSeccion && horarioSeccion.length > 0) {
        horarioSeccion.forEach(fila => {
            const tr = document.createElement('tr');
            
            fila.forEach((celda, index) => {
                const td = document.createElement('td');
                td.textContent = celda;
                tr.appendChild(td);
            });
            
            tbody.appendChild(tr);
        });
    } else {
        // Mensaje si no hay horario disponible
        const tr = document.createElement('tr');
        const td = document.createElement('td');
        td.colSpan = 6;
        td.textContent = 'Horario no disponible para esta sección';
        td.style.textAlign = 'center';
        td.style.padding = '20px';
        tr.appendChild(td);
        tbody.appendChild(tr);
    }
}

// Actualizar título del horario
function actualizarTitulo() {
    const titulo = document.getElementById('titulo-seccion');
    const añoTexto = añoActual === 'primero' ? 'Primer Año' : 'Segundo Año';
    titulo.textContent = `${añoTexto} - Sección ${seccionActual}`;
}                                                                                                                                                                                                                                                                                                                                                                                                                   
