const horarios = {
    "primero": {
        "1-1": [
            ["7:00 AM - 7:45 AM", "CIENCIA Y TECNOLOGÍA", "CIENCIA Y TECNOLOGÍA", "CIENCIA Y TECNOLOGÍA", "FRANCÉS", "MÓDULO"],
            ["7:45 AM - 8:30 AM", "CIENCIA Y TECNOLOGÍA", "CIENCIA Y TECNOLOGÍA", "CIENCIA Y TECNOLOGÍA", "FRANCÉS", "MÓDULO"],
            ["8:30 AM - 8:45 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["8:45 AM - 9:30 AM", "MOD 1.5 ST", "MÓDULO", "EDUCACION FISICA", "MÓDULO", "CIUDADANIA Y VALORES"],
            ["9:30 AM - 10:15 AM", "MOD 1.5 ST", "MÓDULO", "EDUCACION FISICA", "MÓDULO", "CIUDADANIA Y VALORES"],
            ["10:15 AM - 10:30 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["10:30 AM - 11:15 PM", "MÓDULO", "MÓDULO", "CIUDADANIA Y VALORES", "MÓDULO", "FRANCÉS"],
            ["11:15 PM - 12:00 PM", "MÓDULO", "MÓDULO", "CIUDADANIA Y VALORES", "MÓDULO", "FRANCÉS"],
            ["12:00 PM - 1:00 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["1:00 PM - 1:45 PM", "", "PRECÁLCULO", "", "PRECÁLCULO", "INGLES"],
            ["1:45 PM - 2:30 PM", "", "PRECÁLCULO", "", "PRECÁLCULO", "INGLES"],
            ["2:30 PM - 2:45 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["2:45 PM - 3:30 PM", "", "LENGUA Y LITERATURA", "PRECÁLCULO", "MOD 1.3 ST", ""],
            ["3:30 PM - 4:15 PM", "", "LENGUA Y LITERATURA", "PRECÁLCULO", "MOD 1.3 ST", ""],
            ["4:15 PM - 4:30 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["4:30 PM - 5:15 PM", "", "LENGUA Y LITERATURA", "LENGUA Y LITERATURA", "INGLÉS", ""],
            ["5:15 PM - 6:00 PM", "", "", "LENGUA Y LITERATURA", "INGLÉS", ""],
        ],
        "1-2": [
            ["7:00 AM - 7:45 AM", "MÓDULO", "MÓDULO", "MÓDULO", "CIENCIA Y TECNOLOGÍA", "EDUCACIÓN FÍSICA"],
            ["7:45 AM - 8:30 AM", "MÓDULO", "MÓDULO", "MÓDULO", "CIENCIA Y TECNOLOGÍA", "EDUCACIÓN FÍSICA"],
            ["8:30 AM - 8:45 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["8:45 AM - 9:30 AM", "MÓDULO", "CIUDADANIA Y VALORES", "MÓDULO", "CIUDADANIA Y VALORES", "MÓDULO"],
            ["9:30 AM - 10:15 AM", "MÓDULO", "CIUDADANIA Y VALORES", "MÓDULO", "CIUDADANIA Y VALORES", "MÓDULO"],
            ["10:15 AM - 10:30 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["10:30 AM - 11:15 PM", "CIUDADANIA Y VALORES", "LENGUA Y LITERATURA", "MOD 1.5 ST", "CIUDADANIA Y VALORES", "CIENCIA Y TECNOLOGÍA"],
            ["11:15 PM - 12:00 PM", "CIUDADANIA Y VALORES", "LENGUA Y LITERATURA", "MOD 1.5 ST", "", "CIENCIA Y TECNOLOGÍA"],
            ["12:00 PM - 1:00 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["1:00 PM - 1:45 PM", "LENGUA Y LITERATURA", "", "FRANCÉS", "INGLÉS", "PRECÁLCULO"],
            ["1:45 PM - 2:30 PM", "LENGUA Y LITERATURA", "", "FRANCÉS", "INGLÉS", "PRECÁLCULO"],
            ["2:30 PM - 2:45 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["2:45 PM - 3:30 PM", "LENGUA Y LITERATURA", "", "FRANCÉS", "PRECÁLCULO", "MOD 1.3 ST"],
            ["3:30 PM - 4:15 PM", "", "", "", "PRECÁLCULO", "MOD 1.3 ST"],
            ["4:15 PM - 4:30 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["4:30 PM - 5:15 PM", "PRECÁLCULO", "", "", "", "INGLÉS"],
            ["5:15 PM - 6:00 PM", "PRECÁLCULO", "", "", "", "INGLÉS"],
        ],

        "1-3": [
            ["7:00 AM - 7:45 AM", "MOD 1.5 ST", "CIUDADANIA Y VALORES", "EDUCACIÓN FÍSICA", "CIUDADANIA Y VALORES", "LENGUA Y LITERATURA"],
            ["7:45 AM - 8:30 AM", "MOD 1.5 ST", "CIUDADANIA Y VALORES", "EDUCACIÓN FÍSICA", "CIUDADANIA Y VALORES", "LENGUA Y LITERATURA"],
            ["8:30 AM - 8:45 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["8:45 AM - 9:30 AM", "FRANCÉS", "", "CIENCIA Y TECNOLOGÍA", "MOD 1.3 ST", "CIENCIA Y TECNOLOGÍA"],
            ["9:30 AM - 10:15 AM", "FRANCÉS", "LENGUA Y LITERATURA", "CIENCIA Y TECNOLOGÍA", "MOD 1.3 ST", "CIENCIA Y TECNOLOGÍA"],
            ["10:15 AM - 10:30 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["10:30 AM - 11:15 PM", "FRANCÉS", "CIENCIA Y TECNOLOGÍA", "INGLÉS", "LENGUA Y LITERATURA", ""],
            ["11:15 PM - 12:00 PM", "", "CIENCIA Y TECNOLOGÍA", "INGLÉS", "LENGUA Y LITERATURA", "CIUDADANIA Y VALORES"],
            ["12:00 PM - 1:00 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["1:00 PM - 1:45 PM", "MÓDULO", "PRECÁLCULO", "PRECÁLCULO", "", "MÓDULO"],
            ["1:45 PM - 2:30 PM", "MÓDULO", "PRECÁLCULO", "PRECÁLCULO", "", "MÓDULO"],
            ["2:30 PM - 2:45 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["2:45 PM - 3:30 PM", "PRECÁLCULO", "", "MÓDULO", "INGLÉS", "MÓDULO"],
            ["3:30 PM - 4:15 PM", "PRECÁLCULO", "", "MÓDULO", "INGLÉS", "MÓDULO"],
            ["4:15 PM - 4:30 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["4:30 PM - 5:15 PM", "", "", "MÓDULO", "MÓDULO", "PRECÁLCULO"],
            ["5:15 PM - 6:00 PM", "", "", "MÓDULO", "MÓDULO", "PRECÁLCULO"],
        ],

        "1-4": [
            ["7:00 AM - 7:45 AM", "CIUDADANIA Y VALORES", "MOD 1.5 ST", "CIUDADANIA Y VALORES", "INGLÉS", "CIENCIA Y TECNOLOGÍA"],
            ["7:45 AM - 8:30 AM", "CIUDADANIA Y VALORES", "MOD 1.5 ST", "CIUDADANIA Y VALORES", "INGLÉS", "CIENCIA Y TECNOLOGÍA"],
            ["8:30 AM - 8:45 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["8:45 AM - 9:30 AM", "CIENCIA Y TECNOLOGÍA", "", "CIUDADANIA Y VALORES", "EDUCACIÓN FÍSICA", "INGLÉS"],
            ["9:30 AM - 10:15 AM", "CIENCIA Y TECNOLOGÍA", "FRANCÉS", "CIUDADANIA Y VALORES", "EDUCACIÓN FÍSICA", "INGLÉS"],
            ["10:15 AM - 10:30 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["10:30 AM - 11:15 PM", "LENGUA Y LITERATURA", "FRANCÉS", "LENGUA Y LITERATURA", "CIENCIA Y TECNOLOGÍA", ""],
            ["11:15 PM - 12:00 PM", "LENGUA Y LITERATURA", "FRANCÉS", "LENGUA Y LITERATURA", "CIENCIA Y TECNOLOGÍA", ""],
            ["12:00 PM - 1:00 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["1:00 PM - 1:45 PM", "PRECÁLCULO", "MÓDULO", "", "MÓDULO", "PRECÁLCULO"],
            ["1:45 PM - 2:30 PM", "PRECÁLCULO", "MÓDULO", "", "MÓDULO", "PRECÁLCULO"],
            ["2:30 PM - 2:45 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["2:45 PM - 3:30 PM", "MÓDULO", "MÓDULO", "", "MÓDULO", ""],
            ["3:30 PM - 4:15 PM", "MÓDULO", "MÓDULO", "", "MÓDULO", ""],
            ["4:15 PM - 4:30 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["4:30 PM - 5:15 PM", "", "PRECÁLCULO", "", "MOD 1.3 ST", "MÓDULO"],
            ["5:15 PM - 6:00 PM", "", "PRECÁLCULO", "", "MOD 1.3 ST", "MÓDULO"],
        ],

        "1-5": [
            ["7:00 AM - 7:45 AM", "LENGUA Y LITERATURA", "INGLÉS", "CIENCIA Y TECNOLOGÍA", "MOD 1.5 ST", "PRECÁLCULO"],
            ["7:45 AM - 8:30 AM", "LENGUA Y LITERATURA", "INGLÉS", "CIENCIA Y TECNOLOGÍA", "MOD 1.5 ST", "PRECÁLCULO"],
            ["8:30 AM - 8:45 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["8:45 AM - 9:30 AM", "CIUDADANIA Y VALORES", "LENGUA Y LITERATURA", "PRECÁLCULO", "LENGUA Y LITERATURA", "CIENCIA Y TECNOLOGÍA"],
            ["9:30 AM - 10:15 AM", "CIUDADANIA Y VALORES", "LENGUA Y LITERATURA", "PRECÁLCULO", "LENGUA Y LITERATURA", "CIENCIA Y TECNOLOGÍA"],
            ["10:15 AM - 10:30 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["10:30 AM - 11:15 PM", "PRECÁLCULO", "CIUDADANIA Y VALORES", "INGLÉS", "CIENCIA Y TECNOLOGÍA", "EDUCACIÓN FÍSICA"],
            ["11:15 PM - 12:00 PM", "PRECÁLCULO", "CIUDADANIA Y VALORES", "INGLÉS", "CIENCIA Y TECNOLOGÍA", "EDUCACIÓN FÍSICA"],
            ["12:00 PM - 1:00 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["1:00 PM - 1:45 PM", "MÓDULO", "", "MÓDULO", "FRANCÉS", "MÓDULO"],
            ["1:45 PM - 2:30 PM", "MÓDULO", "", "MÓDULO", "FRANCÉS", "MÓDULO"],
            ["2:30 PM - 2:45 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["2:45 PM - 3:30 PM", "", "", "MÓDULO", "FRANCÉS", "MÓDULO"],
            ["3:30 PM - 4:15 PM", "", "", "MÓDULO", "", "MÓDULO"],
            ["4:15 PM - 4:30 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["4:30 PM - 5:15 PM", "", "", "MÓDULO", "", "MOD 1.3 ST"],
            ["5:15 PM - 6:00 PM", "", "", "MÓDULO", "", "MOD 1.3 ST"],
        ],
    

        "1-6": [ 
            ["7:00 AM - 7:45 AM", "PRECALCULO", "PRECALCULO", "MODULO 1.5 ST", "LENGUA Y LITERATURA", "CIENCIA Y TECNOLOGIA"],
            ["7:45 AM - 8:30 AM", "PRECALCULO", "PRECALCULO", "MODULO 1.5 ST", "LENGUA Y LITERATURA", "CIENCIA Y TECNOLOGIA"],
            ["8:30 AM - 8:45 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["8:45 AM - 9:30 AM", "CIENCIA Y TECNOLOGIA", "INGLES", "LENGUA Y LITERATURA", "PRECALCULO", "LENGUA Y LITERATURA"],
            ["9:30 AM - 10:15 AM", "CIENCIA Y TECNOLOGIA", "INGLES", "CIUDADANIA Y VALORES", "PRECALCULO", "LENGUA Y LITERATURA"],
            ["10:15 AM - 10:30 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["10:30 AM - 11:15 PM", "CIUDADANIA Y VALORES", "CIUDADANIA Y VALORES", "CIENCIA Y TECNOLOGIA", "EDUCACION FISICA", "INGLES"],
            ["11:15 PM - 12:00 PM", "CIUDADANIA Y VALORES", "CIUDADANIA Y VALORES", "CIENCIA Y TECNOLOGIA", "EDUCACION FISICA", "INGLES"],
            ["12:00 PM - 1:00 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["1:00 PM - 1:45 PM", "MODULO", "MODULO", "", "MODULO", ""],
            ["1:45 PM - 2:30 PM", "MODULO", "MODULO", "", "MODULO", "FRANCES"],
            ["2:30 PM - 2:45 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["2:45 PM - 3:30 PM", "MODULO", "MODULO", "", "MODULO", "FRANCES"],
            ["3:30 PM - 4:15 PM", "MODULO", "MODULO", "", "MODULO", ""],
            ["4:15 PM - 4:30 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["4:30 PM - 5:15 PM", "MODULO", "MODULO 1.3 ST", "", "", ""],
            ["5:15 PM - 6:00 PM", "MODULO", "MODULO 1.3 ST", "", "", ""],
        ],
    },

    "segundo": {
        "2-1": [
            ["7:00 AM - 7:45 AM", "SALAZAR CARRANZA, BRISEIDA GUADALUPE IDIOMA EXTRANJERO", "SERRANO MOZO, JORGE ADALBERTO\nESTUDIOS SOCIALES Y CÍVICA", "", "MARTELL DE CRISTALES, MARÍA ELIZABETH\nMOD 2.8 ST", "RIVAS MENDOZA, JOSÉ SAÚL\nMOD 2.3 ST"],
            ["7:45 AM - 8:30 AM", "SALAZAR CARRANZA, BRISEIDA GUADALUPE IDIOMA EXTRANJERO", "SERRANO MOZO, JORGE ADALBERTO\nESTUDIOS SOCIALES Y CÍVICA", "", "MARTELL DE CRISTALES, MARÍA ELIZABETH\nMOD 2.8 ST", "RIVAS MENDOZA, JOSÉ SAÚL\nMOD 2.3 ST"],
            ["8:30 AM - 8:45 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["8:45 AM - 9:30 AM", "RIVERA DE NÚÑEZ, BRENDA ISABEL MOD 2.1 ST", "SERRANO MOZO, JORGE ADALBERTO\nESTUDIOS SOCIALES Y CÍVICA", "", "MARTÍNEZ DE ALVARENGA, CLARINA ANGELICA\nORIENTACIÓN PARA LA VIDA", "RIVAS MENDOZA, JOSÉ SAÚL\nMOD 2.3 ST"],
            ["9:30 AM - 10:15 AM", "RIVERA DE NÚÑEZ, BRENDA ISABEL MOD 2.1 ST", "SERRANO MOZO, JORGE ADALBERTO\nESTUDIOS SOCIALES Y CÍVICA", "", "MARTÍNEZ DE ALVARENGA, CLARINA ANGELICA\nORIENTACIÓN PARA LA VIDA", "RIVERA DE NÚÑEZ, BRENDA ISABEL\nMOD 2.2 ST"],
            ["10:15 AM - 10:30 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["10:30 AM - 11:15 AM", "RIVERA DE NÚÑEZ, BRENDA ISABEL MOD 2.2 ST", "SALAZAR CARRANZA, BRISEIDA GUADALUPE\nIDIOMA EXTRANJERO", "", "SALAZAR CARRANZA, BRISEIDA GUADALUPE\nIDIOMA EXTRANJERO", "GRANADOS BLANCO, MARIO DOUGLAS\nEDUCACIÓN FÍSICA"],
            ["11:15 AM - 12:00 PM", "RIVERA DE NÚÑEZ, BRENDA ISABEL MOD 2.2 ST", "SALAZAR CARRANZA, BRISEIDA GUADALUPE\nIDIOMA EXTRANJERO", "", "SALAZAR CARRANZA, BRISEIDA GUADALUPE\nIDIOMA EXTRANJERO", "GRANADOS BLANCO, MARIO DOUGLAS\nEDUCACIÓN FÍSICA"],
            ["12:00 PM - 1:00 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["1:00 PM - 1:45 PM", "LÓPEZ RAMÍREZ, GABRIELA MARISOL LENGUAJE Y LITERATURA", "SANTANA LÓPEZ, ANA SELMA GEORGINA\nMOD 2.7 ST", "LÓPEZ RAMÍREZ, GABRIELA MARISOL\nLENGUAJE Y LITERATURA", "JUÁREZ DE GARCÍA, ROSA ESMERALDA\nMATEMÁTICA", "AGUILAR BERMÚDEZ, SONIA ISABEL\nCIENCIAS NATURALES"],
            ["1:45 PM - 2:30 PM", "LÓPEZ RAMÍREZ, GABRIELA MARISOL LENGUAJE Y LITERATURA", "SANTANA LÓPEZ, ANA SELMA GEORGINA\nMOD 2.7 ST", "LÓPEZ RAMÍREZ, GABRIELA MARISOL\nLENGUAJE Y LITERATURA", "JUÁREZ DE GARCÍA, ROSA ESMERALDA\nMATEMÁTICA", "AGUILAR BERMÚDEZ, SONIA ISABEL\nCIENCIAS NATURALES"],
            ["2:30 PM - 2:45 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["2:45 PM - 3:30 PM", "JUÁREZ DE GARCÍA, ROSA ESMERALDA MATEMÁTICA", "RIVAS MENDOZA, JOSÉ SAÚL\nMOD 2.4 ST", "LÓPEZ RAMÍREZ, GABRIELA MARISOL\nLENGUAJE Y LITERATURA", "RIVAS MENDOZA, JOSÉ SAÚL\nMOD 2.5 ST", ""],
            ["3:30 PM - 4:15 PM", "JUÁREZ DE GARCÍA, ROSA ESMERALDA MATEMÁTICA", "RIVAS MENDOZA, JOSÉ SAÚL\nMOD 2.4 ST", "", "RIVAS MENDOZA, JOSÉ SAÚL\nMOD 2.5 ST", "CARRANZA GÓMEZ, OVELAS NESTOR EFREN\nFRANCÉS"],
            ["4:15 PM - 4:30 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["4:30 PM - 5:15 PM", "POLIO CORTEZ, GERBER ALEXANDER MOD 2.6 ST", "JUÁREZ DE GARCÍA, ROSA ESMERALDA\nMATEMÁTICA", "AGUILAR BERMÚDEZ, SONIA ISABEL\nCIENCIAS NATURALES", "AGUILAR BERMÚDEZ, SONIA ISABEL\nCIENCIAS NATURALES", "CARRANZA GÓMEZ, OVELAS NESTOR EFREN\nFRANCÉS"],
            ["5:15 PM - 6:00 PM", "POLIO CORTEZ, GERBER ALEXANDER MOD 2.6 ST", "JUÁREZ DE GARCÍA, ROSA ESMERALDA\nMATEMÁTICA", "AGUILAR BERMÚDEZ, SONIA ISABEL\nCIENCIAS NATURALES", "AGUILAR BERMÚDEZ, SONIA ISABEL\nCIENCIAS NATURALES", "CARRANZA GÓMEZ, OVELAS NESTOR EFREN\nFRANCÉS"],
        ],

        "2-2": [
            ["7:00 AM - 7:45 AM", "RIVERA DE NÚÑEZ, BRENDA ISABEL\nMOD 2.1 ST", "RIVERA DE NÚÑEZ, BRENDA ISABEL\nMOD 2.2 ST", "RIVAS MENDOZA, JOSÉ SAÚL\nMOD 2.4 ST", "POLIO CORTEZ, GERBER ALEXANDER\nMOD 2.6 ST", "GRANADOS BLANCO, MARIO DOUGLAS\nEDUCACIÓN FÍSICA"],
            ["7:45 AM - 8:30 AM", "RIVERA DE NÚÑEZ, BRENDA ISABEL\nMOD 2.1 ST", "RIVERA DE NÚÑEZ, BRENDA ISABEL\nMOD 2.2 ST", "RIVAS MENDOZA, JOSÉ SAÚL\nMOD 2.4 ST", "POLIO CORTEZ, GERBER ALEXANDER\nMOD 2.6 ST", "GRANADOS BLANCO, MARIO DOUGLAS\nEDUCACIÓN FÍSICA"],
            ["8:30 AM - 8:45 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["8:45 AM - 9:30 AM", "MARTÍNEZ DE ALVARENGA, CLARINA ANGELICA\nORIENTACIÓN PARA LA VIDA", "RIVERA DE NÚÑEZ, BRENDA ISABEL\nMOD 2.2 ST", "RIVAS MENDOZA, JOSÉ SAÚL\nMOD 2.5 ST", "SALAZAR CARRANZA, BRISEIDA GUADALUPE\nIDIOMA EXTRANJERO", "SERRANO MOZO, JORGE ADALBERTO\nESTUDIOS SOCIALES Y CÍVICA"],
            ["9:30 AM - 10:15 AM", "MARTÍNEZ DE ALVARENGA, CLARINA ANGELICA\nORIENTACIÓN PARA LA VIDA", "SERRANO MOZO, JORGE ADALBERTO\nESTUDIOS SOCIALES Y CÍVICA", "RIVAS MENDOZA, JOSÉ SAÚL\nMOD 2.5 ST", "SALAZAR CARRANZA, BRISEIDA GUADALUPE\nIDIOMA EXTRANJERO", "SERRANO MOZO, JORGE ADALBERTO\nESTUDIOS SOCIALES Y CÍVICA"],
            ["10:15 AM - 10:30 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["10:30 AM - 11:15 PM", "RIVAS MENDOZA, JOSÉ SAÚL\nMOD 2.3 ST", "SERRANO MOZO, JORGE ADALBERTO\nESTUDIOS SOCIALES Y CÍVICA", "SALAZAR CARRANZA, BRISEIDA GUADALUPE\nIDIOMA EXTRANJERO", "SALAZAR CARRANZA, BRISEIDA GUADALUPE\nIDIOMA EXTRANJERO", "MARTELL DE CRISTALES, MARÍA ELIZABETH\nMOD 2.8 ST"],
            ["11:15 PM - 12:00 PM", "", "SERRANO MOZO, JORGE ADALBERTO\nESTUDIOS SOCIALES Y CÍVICA", "SALAZAR CARRANZA, BRISEIDA GUADALUPE\nIDIOMA EXTRANJERO", "SALAZAR CARRANZA, BRISEIDA GUADALUPE\nIDIOMA EXTRANJERO", "MARTELL DE CRISTALES, MARÍA ELIZABETH\nMOD 2.8 ST"],
            ["12:00 PM - 1:00 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["1:00 PM - 1:45 PM", "CARRANZA GÓMEZ, OVELAS NESTOR EFREN\nFRANCÉS", "JUÁREZ DE GARCÍA, ROSA ESMERALDA\nMATEMÁTICA", "AGUILAR BERMÚDEZ, SONIA ISABEL\nCIENCIAS NATURALES", "RIVAS MENDOZA, JOSÉ SAÚL\nMOD 2.3 ST", "GUARDADO ALBERTO DE MELARA, SANDRA ARELY\nMOD 2.7 ST"],
            ["1:45 PM - 2:30 PM", "CARRANZA GÓMEZ, OVELAS NESTOR EFREN\nFRANCÉS", "JUÁREZ DE GARCÍA, ROSA ESMERALDA\nMATEMÁTICA", "AGUILAR BERMÚDEZ, SONIA ISABEL\nCIENCIAS NATURALES", "RIVAS MENDOZA, JOSÉ SAÚL\nMOD 2.3 ST", "GUARDADO ALBERTO DE MELARA, SANDRA ARELY\nMOD 2.7 ST"],
            ["2:30 PM - 2:45 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["2:45 PM - 3:30 PM", "CARRANZA GÓMEZ, OVELAS NESTOR EFREN\nFRANCÉS", "AGUILAR BERMÚDEZ, SONIA ISABEL\nCIENCIAS NATURALES", "JUÁREZ DE GARCÍA, ROSA ESMERALDA\nMATEMÁTICA", "AGUILAR BERMÚDEZ, SONIA ISABEL\nCIENCIAS NATURALES", "LÓPEZ RAMÍREZ, GABRIELA MARISOL\nLENGUAJE Y LITERATURA"],
            ["3:30 PM - 4:15 PM", "LÓPEZ RAMÍREZ, GABRIELA MARISOL\nLENGUAJE Y LITERATURA", "AGUILAR BERMÚDEZ, SONIA ISABEL\nCIENCIAS NATURALES", "JUÁREZ DE GARCÍA, ROSA ESMERALDA\nMATEMÁTICA", "AGUILAR BERMÚDEZ, SONIA ISABEL\nCIENCIAS NATURALES", "LÓPEZ RAMÍREZ, GABRIELA MARISOL\nLENGUAJE Y LITERATURA"],
            ["4:15 PM - 4:30 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["4:30 PM - 5:15 PM", "LÓPEZ RAMÍREZ, GABRIELA MARISOL\nLENGUAJE Y LITERATURA", "", "", "", "JUÁREZ DE GARCÍA, ROSA ESMERALDA\nMATEMÁTICA"],
            ["5:15 PM - 6:00 PM", "LÓPEZ RAMÍREZ, GABRIELA MARISOL\nLENGUAJE Y LITERATURA", "", "", "", "JUÁREZ DE GARCÍA, ROSA ESMERALDA\nMATEMÁTICA"],

        ],


        "2-3": [
            ["7:00 AM - 7:45 AM", "RIVAS MENDOZA, JOSÉ SAÚL\nMOD 2.4 ST", "SALAZAR CARRANZA, BRISEIDA GUADALUPE\nIDIOMA EXTRANJERO", "GRANADOS BLANCO, MARIO DOUGLAS\nEDUCACIÓN FÍSICA", "RIVERA DE NÚÑEZ, BRENDA ISABEL\nMOD 2.3 ST", "SERRANO MOZO, JORGE ADALBERTO\nESTUDIOS SOCIALES Y CÍVICA"],
            ["7:45 AM - 8:30 AM", "RIVAS MENDOZA, JOSÉ SAÚL\nMOD 2.4 ST", "SALAZAR CARRANZA, BRISEIDA GUADALUPE\nIDIOMA EXTRANJERO", "GRANADOS BLANCO, MARIO DOUGLAS\nEDUCACIÓN FÍSICA", "SERRANO MOZO, JORGE ADALBERTO\nESTUDIOS SOCIALES Y CÍVICA", "SERRANO MOZO, JORGE ADALBERTO\nESTUDIOS SOCIALES Y CÍVICA"],
            ["8:30 AM - 8:45 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["8:45 AM - 9:30 AM", "RIVAS MENDOZA, JOSÉ SAÚL\nMOD 2.5 ST", "SALAZAR CARRANZA, BRISEIDA GUADALUPE\nIDIOMA EXTRANJERO", "RIVERA DE NÚÑEZ, BRENDA ISABEL\nMOD 2.1 ST", "SERRANO MOZO, JORGE ADALBERTO\nESTUDIOS SOCIALES Y CÍVICA", "SALAZAR CARRANZA, BRISEIDA GUADALUPE\nIDIOMA EXTRANJERO"],            ["9:30 AM - 10:15 AM", "RIVAS MENDOZA, JOSÉ SAÚL\nMOD 2.5 ST", "SALAZAR CARRANZA, BRISEIDA GUADALUPE\nIDIOMA EXTRANJERO", "RIVERA DE NÚÑEZ, BRENDA ISABEL\nMOD 2.1 ST", "SERRANO MOZO, JORGE ADALBERTO\nESTUDIOS SOCIALES Y CÍVICA", "SALAZAR CARRANZA, BRISEIDA GUADALUPE\nIDIOMA EXTRANJERO"],
            ["10:15 AM - 10:30 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["10:30 AM - 11:15 PM", "POLIO CORTEZ, GERBER ALEXANDER\nMOD 2.6 ST", "RIVERA DE NÚÑEZ, BRENDA ISABEL\nMOD 2.2 ST", "RIVAS MENDOZA, JOSÉ SAÚL\nMOD 2.7 ST", "MARTÍNEZ DE ALVARENGA, CLARINA ANGELICA\nORIENTACIÓN PARA LA VIDA", "RIVERA DE NÚÑEZ, BRENDA ISABEL\nMOD 2.3 ST"],
            ["11:15 PM - 12:00 PM", "POLIO CORTEZ, GERBER ALEXANDER\nMOD 2.6 ST", "RIVERA DE NÚÑEZ, BRENDA ISABEL\nMOD 2.2 ST", "RIVAS MENDOZA, JOSÉ SAÚL\nMOD 2.7 ST", "MARTÍNEZ DE ALVARENGA, CLARINA ANGELICA\nORIENTACIÓN PARA LA VIDA", "RIVERA DE NÚÑEZ, BRENDA ISABEL\nMOD 2.3 ST"],
            ["12:00 PM - 1:00 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["1:00 PM - 1:45 PM", "AGUILAR BERMÚDEZ, SONIA ISABEL\nCIENCIAS NATURALES", "LÓPEZ RAMÍREZ, GABRIELA MARISOL\nLENGUAJE Y LITERATURA", "MARTÍNEZ DE ELÍAS, CLAUDIA RAQUEL\nMOD 2.8 ST", "AGUILAR BERMÚDEZ, SONIA ISABEL\nCIENCIAS NATURALES", "LÓPEZ RAMÍREZ, GABRIELA MARISOL\nLENGUAJE Y LITERATURA"],
            ["1:45 PM - 2:30 PM", "AGUILAR BERMÚDEZ, SONIA ISABEL\nCIENCIAS NATURALES", "LÓPEZ RAMÍREZ, GABRIELA MARISOL\nLENGUAJE Y LITERATURA", "MARTÍNEZ DE ELÍAS, CLAUDIA RAQUEL\nMOD 2.8 ST", "AGUILAR BERMÚDEZ, SONIA ISABEL\nCIENCIAS NATURALES", "LÓPEZ RAMÍREZ, GABRIELA MARISOL\nLENGUAJE Y LITERATURA"],
            ["2:30 PM - 2:45 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["2:45 PM - 3:30 PM", "", "LÓPEZ RAMÍREZ, GABRIELA MARISOL\nLENGUAJE Y LITERATURA", "AGUILAR BERMÚDEZ, SONIA ISABEL\nCIENCIAS NATURALES", "JUÁREZ DE GARCÍA, ROSA ESMERALDA\nMATEMÁTICA", "JUÁREZ DE GARCÍA, ROSA ESMERALDA\nMATEMÁTICA"],
            ["3:30 PM - 4:15 PM", "CARRANZA GÓMEZ, OVELAS NESTOR EFREN\nFRANCÉS", "", "AGUILAR BERMÚDEZ, SONIA ISABEL\nCIENCIAS NATURALES", "JUÁREZ DE GARCÍA, ROSA ESMERALDA\nMATEMÁTICA", "JUÁREZ DE GARCÍA, ROSA ESMERALDA\nMATEMÁTICA"],
            ["4:15 PM - 4:30 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["4:30 PM - 5:15 PM", "", "CARRANZA GÓMEZ, OVELAS NESTOR EFREN\nFRANCÉS", "JUÁREZ DE GARCÍA, ROSA ESMERALDA\nMATEMÁTICA", "", ""],
            ["5:15 PM - 6:00 PM", "", "CARRANZA GÓMEZ, OVELAS NESTOR EFREN\nFRANCÉS", "JUÁREZ DE GARCÍA, ROSA ESMERALDA\nMATEMÁTICA", "", ""],
        ],

        "2-4": [
            ["7:00 AM - 7:45 AM", "SERRANO MOZO, JORGE ADALBERTO\nESTUDIOS SOCIALES Y CÍVICA", "RIVAS MENDOZA, JOSÉ SAÚL\nMOD 2.7 ST", "RIVERA DE NÚÑEZ, BRENDA ISABEL\nMOD 2.1 ST", "SALAZAR CARRANZA, BRISEIDA GUADALUPE\nIDIOMA EXTRANJERO", "RIVERA DE NÚÑEZ, BRENDA ISABEL\nMOD 2.2 ST"],
            ["7:45 AM - 8:30 AM", "SERRANO MOZO, JORGE ADALBERTO\nESTUDIOS SOCIALES Y CÍVICA", "RIVAS MENDOZA, JOSÉ SAÚL\nMOD 2.7 ST", "RIVERA DE NÚÑEZ, BRENDA ISABEL\nMOD 2.1 ST", "SALAZAR CARRANZA, BRISEIDA GUADALUPE\nIDIOMA EXTRANJERO", "RIVERA DE NÚÑEZ, BRENDA ISABEL\nMOD 2.2 ST"],
            ["8:30 AM - 8:45 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["8:45 AM - 9:30 AM", "SERRANO MOZO, JORGE ADALBERTO\nESTUDIOS SOCIALES Y CÍVICA", "MARTÍNEZ DE ALVARENGA, CLARINA ANGELICA\nORIENTACIÓN PARA LA VIDA", "SERRANO MOZO, JORGE ADALBERTO\nESTUDIOS SOCIALES Y CÍVICA", "RIVAS MENDOZA, JOSÉ SAÚL\nMOD 2.4 ST", "RIVERA DE NÚÑEZ, BRENDA ISABEL\nMOD 2.2 ST"],
            ["9:30 AM - 10:15 AM", "SALAZAR CARRANZA, BRISEIDA GUADALUPE\nIDIOMA EXTRANJERO", "MARTÍNEZ DE ALVARENGA, CLARINA ANGELICA\nORIENTACIÓN PARA LA VIDA", "SERRANO MOZO, JORGE ADALBERTO\nESTUDIOS SOCIALES Y CÍVICA", "RIVAS MENDOZA, JOSÉ SAÚL\nMOD 2.4 ST", "RIVAS MENDOZA, JOSÉ SAÚL\nMOD 2.3 ST"],
            ["10:15 AM - 10:30 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["10:30 AM - 11:15 AM", "SALAZAR CARRANZA, BRISEIDA GUADALUPE\nIDIOMA EXTRANJERO", "POLIO CORTEZ, GERBER ALEXANDER\nMOD 2.6 ST", "GRANADOS BLANCO, MARIO DOUGLAS\nEDUCACIÓN FÍSICA", "RIVAS MENDOZA, JOSÉ SAÚL\nMOD 2.5 ST", "RIVAS MENDOZA, JOSÉ SAÚL\nMOD 2.3 ST"],
            ["11:15 AM - 12:00 PM", "SALAZAR CARRANZA, BRISEIDA GUADALUPE\nIDIOMA EXTRANJERO", "POLIO CORTEZ, GERBER ALEXANDER\nMOD 2.6 ST", "GRANADOS BLANCO, MARIO DOUGLAS\nEDUCACIÓN FÍSICA", "RIVAS MENDOZA, JOSÉ SAÚL\nMOD 2.5 ST", "RIVAS MENDOZA, JOSÉ SAÚL\nMOD 2.3 ST"],
            ["12:00 PM - 1:00 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["1:00 PM - 1:45 PM", "JUÁREZ DE GARCÍA, ROSA ESMERALDA\nMATEMÁTICA", "AGUILAR BERMÚDEZ, SONIA ISABEL\nCIENCIAS NATURALES", "", "LÓPEZ RAMÍREZ, GABRIELA MARISOL\nLENGUAJE Y LITERATURA", "JUÁREZ DE GARCÍA, ROSA ESMERALDA\nMATEMÁTICA"],
            ["1:45 PM - 2:30 PM", "JUÁREZ DE GARCÍA, ROSA ESMERALDA\nMATEMÁTICA", "AGUILAR BERMÚDEZ, SONIA ISABEL\nCIENCIAS NATURALES", "", "LÓPEZ RAMÍREZ, GABRIELA MARISOL\nLENGUAJE Y LITERATURA", "JUÁREZ DE GARCÍA, ROSA ESMERALDA\nMATEMÁTICA"],
            ["2:30 PM - 2:45 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["2:45 PM - 3:30 PM", "AGUILAR BERMÚDEZ, SONIA ISABEL\nCIENCIAS NATURALES", "JUÁREZ DE GARCÍA, ROSA ESMERALDA\nMATEMÁTICA", "", "LÓPEZ RAMÍREZ, GABRIELA MARISOL\nLENGUAJE Y LITERATURA", "MARTÍNEZ DE ELÍAS, CLAUDIA RAQUEL\nMOD 2.8 ST"],
            ["3:30 PM - 4:15 PM", "AGUILAR BERMÚDEZ, SONIA ISABEL\nCIENCIAS NATURALES", "JUÁREZ DE GARCÍA, ROSA ESMERALDA\nMATEMÁTICA", "", "CARRANZA GÓMEZ, OVELAS NESTOR EFREN\nFRANCÉS", "MARTÍNEZ DE ELÍAS, CLAUDIA RAQUEL\nMOD 2.8 ST"],
            ["4:15 PM - 4:30 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["4:30 PM - 5:15 PM", "", "LÓPEZ RAMÍREZ, GABRIELA MARISOL\nLENGUAJE Y LITERATURA", "", "CARRANZA GÓMEZ, OVELAS NESTOR EFREN\nFRANCÉS", "AGUILAR BERMÚDEZ, SONIA ISABEL\nCIENCIAS NATURALES"],
            ["5:15 PM - 6:00 PM", "", "LÓPEZ RAMÍREZ, GABRIELA MARISOL\nLENGUAJE Y LITERATURA", "", "CARRANZA GÓMEZ, OVELAS NESTOR EFREN\nFRANCÉS", "AGUILAR BERMÚDEZ, SONIA ISABEL\nCIENCIAS NATURALES"],
        ],
        "2-5": [
            ["7:00 AM - 7:45 AM", "GARCIA NAVARO CARLOS HUMBERTO CIENCIAS NATURALES", "GARCIA NAVARO CARLOS HUMBERTO CIENCIAS NAURALES", "SERRANO MONZO JORGE ADALBERTO ESTUDIO SOCIALES", "RIVAS MENDOZA JOSE SAUL MOD 2.3 ST", "SALAZAR CARANZA BRESISEIDA GUADALUPE IDIOMA EXTRANJERO"],
            ["7:45 AM - 8:30 AM", "GARCIA NAVARO CARLOS HUMBERTO CIENCIAS NATURALES", "GARCIA NAVARO CARLOS HUMBERTO CIENCIAS NATURALES", "SERRANO MONZO JORGE ADALBERTO ESTUDIO SOCIALES", "RIVAS MENDOZA JOSE SAUL MOD 2.3 ST", "SALAZAR CARANZA BREISAIDA GUADALUPE IDIOMA EXTRANJERO"],
            ["8:30 AM - 8:45 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["8:45 AM - 9:30 AM", "SALAZAR CARRANZA, BRISEIDA GUADALUPE IDIOMA EXTRANJERO", "RIVAS MENDOZA JOSE SAUL MOD 2.4, SALAZAR CARRANZA, BRISEIDA GUADALUPE IDIOMA EXTRANJERO", "REVERAS NUÑES BRNDA ISABEL MOD 2.1", "GRANADOS BLANCO MARIO DOUGLAS ",],
            ["9:30 AM - 10:15 AM", "SALAZAR CARRANZA, BRISEIDA GUADALUPE IDIOMA EXTRANJERO", "RIVAS MENDOZA JOSE SAUL MOD 2.4", "SALAZAR CARRANZA, BRISEIDA GUADALUPE IDIOMA EXTRANJERO", "REVERAS NUÑES BRNDA ISABEL MOD 2.1", "GRANADOS BLANCO MARIO DOUGLAS"],
            ["10:15 AM - 10:30 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["10:30 AM - 11:15 AM", "SALAZAR CARRANZA, BRISEIDA GUADALUPE\nIDIOMA EXTRANJERO", "POLIO CORTEZ, GERBER ALEXANDER\nMOD 2.6 ST", "GRANADOS BLANCO, MARIO DOUGLAS\nEDUCACIÓN FÍSICA", "RIVERA DE NUÑES BRENDA ISABEL MOD 2.1", "RIVAS MENDOZA, JOSÉ SAÚL\nMOD 2.3 ST"],
            ["11:15 AM - 12:00 PM", "SALAZAR CARRANZA, BRISEIDA GUADALUPE\nIDIOMA EXTRANJERO", "POLIO CORTEZ, GERBER ALEXANDER\nMOD 2.6 ST", "GRANADOS BLANCO, MARIO DOUGLAS\nEDUCACIÓN FÍSICA", "", "RIVAS MENDOZA, JOSÉ SAÚL\nMOD 2.3 ST"],
            ["12:00 PM - 1:00 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["1:00 PM - 1:45 PM", "JUÁREZ DE GARCÍA, ROSA ESMERALDA\nMATEMÁTICA", "AGUILAR BERMÚDEZ, SONIA ISABEL\nCIENCIAS NATURALES", "", "LÓPEZ RAMÍREZ, GABRIELA MARISOL\nLENGUAJE Y LITERATURA", "JUÁREZ DE GARCÍA, ROSA ESMERALDA\nMATEMÁTICA"],
            ["1:45 PM - 2:30 PM", "JUÁREZ DE GARCÍA, ROSA ESMERALDA\nMATEMÁTICA", "AGUILAR BERMÚDEZ, SONIA ISABEL\nCIENCIAS NATURALES", "", "LÓPEZ RAMÍREZ, GABRIELA MARISOL\nLENGUAJE Y LITERATURA", "JUÁREZ DE GARCÍA, ROSA ESMERALDA\nMATEMÁTICA"],
            ["2:30 PM - 2:45 PM", "", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["2:45 PM - 3:30 PM", " BERMÚDEZ, SONIA ISABEL\nCIENCIAS NATURALES", "JUÁREZ DE GARCÍA, ROSA ESMERALDA\nMATEMÁTICA", "", "LÓPEZ RAMÍREZ, GABRIELA MARISOL\nLENGUAJE Y LITERATURA", "MARTÍNEZ DE ELÍAS, CLAUDIA RAQUEL\nMOD 2.8 ST"],
            ["3:30 PM - 4:15 PM", "AGUILAR BERMÚDEZ, SONIA ISABEL\nCIENCIAS NATURALES", "JUÁREZ DE GARCÍA, ROSA ESMERALDA\nMATEMÁTICA", "", "CARRANZA GÓMEZ, OVELAS NESTOR EFREN\nFRANCÉS", "MARTÍNEZ DE ELÍAS, CLAUDIA RAQUEL\nMOD 2.8 ST"],
            ["4:15 PM - 4:30 PM", "", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["4:30 PM - 5:15 PM", "", "LÓPEZ RAMÍREZ, GABRIELA MARISOL\nLENGUAJE Y LITERATURA", "", "CARRANZA GÓMEZ, OVELAS NESTOR EFREN\nFRANCÉS", "AGUILAR BERMÚDEZ, SONIA ISABEL\nCIENCIAS NATURALES"],
            ["5:15 PM - 6:00 PM", "", "LÓPEZ RAMÍREZ, GABRIELA MARISOL\nLENGUAJE Y LITERATURA", "", "CARRANZA GÓMEZ, OVELAS NESTOR EFREN\nFRANCÉS", "AGUILAR BERMÚDEZ, SONIA ISABEL\nCIENCIAS NATURALES"],
        ], 
    },

    "tercero": {
        "3-1": [
            ["7:00 AM - 7:45 AM", "MARTÍNEZ DE ELÍAS, CLAUDIA RAQUEL\nMOD 3.7 ST", "MARTÍNEZ DE ELÍAS, CLAUDIA RAQUEL\nMOD 3.8 ST", "VENTURA SANTOS, SALOME DANILO\nMOD 3.4 ST", "VENTURA SANTOS, SALOME DANILO\nMOD 3.4 ST", "ZAMORA VENTURA, MARTA CONSUELO\nMOD 3.1 ST"],
            ["7:45 AM - 8:30 AM", "MARTÍNEZ DE ELÍAS, CLAUDIA RAQUEL\nMOD 3.7 ST", "MARTÍNEZ DE ELÍAS, CLAUDIA RAQUEL\nMOD 3.8 ST", "VENTURA SANTOS, SALOME DANILO\nMOD 3.4 ST", "VENTURA SANTOS, SALOME DANILO\nMOD 3.4 ST", "ZAMORA VENTURA, MARTA CONSUELO\nMOD 3.1 ST"],
            ["8:30 AM - 8:45 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["8:45 AM - 9:30 AM", "VENTURA SANTOS, SALOME DANILO\nMOD 3.3 ST", "ZAMORA VENTURA, MARTA CONSUELO\nMOD 3.5 ST", "ACEVEDO BENÍTEZ, CLAUDIA MAGDALENA\nMOD 3.2 ST", "VENTURA SANTOS, SALOME DANILO\nMOD 3.3 ST", "MARTÍNEZ DE ELÍAS, CLAUDIA RAQUEL\nMOD 3.8 ST"],
            ["9:30 AM - 10:15 AM", "VENTURA SANTOS, SALOME DANILO\nMOD 3.3 ST", "ZAMORA VENTURA, MARTA CONSUELO\nMOD 3.5 ST", "ACEVEDO BENÍTEZ, CLAUDIA MAGDALENA\nMOD 3.2 ST", "VENTURA SANTOS, SALOME DANILO\nMOD 3.3 ST", "MARTÍNEZ DE ELÍAS, CLAUDIA RAQUEL\nMOD 3.8 ST"],
            ["10:15 AM - 10:30 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["10:30 AM - 11:15 AM", "ZAMORA VENTURA, MARTA CONSUELO\nMOD 3.1 ST", "ZAMORA VENTURA, MARTA CONSUELO\nMOD 3.5 ST", "POLIO CORTEZ, GERBER ALEXANDER\nMOD 3.6 ST", "ZAMORA VENTURA, MARTA CONSUELO\nMOD 3.1 ST", "ACEVEDO BENÍTEZ, CLAUDIA MAGDALENA\nMOD 3.2 ST"],
            ["11:15 AM - 12:00 PM", "ZAMORA VENTURA, MARTA CONSUELO\nMOD 3.1 ST", "VENTURA SANTOS, SALOME DANILO\nMOD 3.3 ST", "POLIO CORTEZ, GERBER ALEXANDER\nMOD 3.6 ST", "ZAMORA VENTURA, MARTA CONSUELO\nMOD 3.1 ST", "ACEVEDO BENÍTEZ, CLAUDIA MAGDALENA\nMOD 3.2 ST"],
            ["12:00 PM - 1:00 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["1:00 PM - 1:45 PM", "", "", "", "", ""],
            ["1:45 PM - 2:30 PM", "", "", "", "", ""],
            ["2:30 PM - 2:45 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["2:45 PM - 3:30 PM", "", "", "", "", ""],
            ["3:30 PM - 4:15 PM", "", "", "", "", ""],
            ["4:15 PM - 4:30 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["4:30 PM - 5:15 PM", "", "", "", "", ""],
            ["5:15 PM - 6:00 PM", "", "", "", "", ""],
        ],

        "3-2": [
            ["7:00 AM - 7:45 AM", "VENTURA SANTOS, SALOME DANILO MOD 3.3 ST","ZAMORA VENTURA, MARTA CONSUELO MOD 3.5 ST","ZAMORA VENTURA, MARTA CONSUELO MOD 3.1 ST","MARTÍNEZ  DE ELÍAS, CLAUDIA RAQUEL MOD 3.7 ST","VENTURA SANTOS, SALOME DANILO MOD 3.4 ST"],
            ["7:45 AM - 8:30 AM", "VENTURA SANTOS, SALOME DANILO MOD 3.3 ST","ZAMORA VENTURA, MARTA CONSUELO MOD 3.5 ST","ZAMORA VENTURA, MARTA CONSUELO MOD 3.1 ST","MARTÍNEZ  DE ELÍAS, CLAUDIA RAQUEL MOD 3.7 ST","VENTURA SANTOS, SALOME DANILO MOD 3.4 ST"],
            ["8:30 AM - 8:45 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["8:45 AM - 9:30 AM", "ZAMORA VENTURA, MARTA CONSUELO MOD 3.1 ST","ACEVEDO BENÍTEZ, CLAUDIA MAGDALENA MOD 3.2 ST","POLIO CORTEZ, GERBER ALEXANDER MOD 3.6 ST","ZAMORA VENTURA, MARTA CONSUELO MOD 3.1 ST","VENTURA SANTOS, SALOME DANILO MOD 3.3 ST"],
            ["9:30 AM - 10:15 AM", "ZAMORA VENTURA, MARTA CONSUELO MOD 3.1 ST","ACEVEDO BENÍTEZ, CLAUDIA MAGDALENA MOD 3.2 S","POLIO CORTEZ, GERBER ALEXANDER MOD 3.6 ST","ZAMORA VENTURA, MARTA CONSUELO MOD 3.1 ST","VENTURA SANTOS, SALOME DANILO MOD 3.3 ST"],
            ["10:15 AM - 10:30 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["10:30 AM - 11:15 AM", "MARTÍNEZ  DE ELÍAS, CLAUDIA RAQUEL MOD 3.8 ST","MARTÍNEZ  DE ELÍAS, CLAUDIA RAQUEL MOD 3.8 ST","VENTURA SANTOS, SALOME DANILO MOD 3.4 ST","ACEVEDO BENÍTEZ, CLAUDIA MAGDALENA MOD 3.2 ST","VENTURA SANTOS, SALOME DANILO MOD 3.3 ST"],
            ["11:15 AM - 12:00 PM", "MARTÍNEZ  DE ELÍAS, CLAUDIA RAQUEL MOD 3.8 ST","MARTÍNEZ  DE ELÍAS, CLAUDIA RAQUEL MOD 3.8 ST","VENTURA SANTOS, SALOME DANILO MOD 3.4 ST","ACEVEDO BENÍTEZ, CLAUDIA MAGDALENA MOD 3.2 ST","VENTURA SANTOS, SALOME DANILO MOD 3.5 ST"],
            ["12:00 PM - 1:00 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["1:00 PM - 1:45 PM", "", "", "", "", ""],
            ["1:45 PM - 2:30 PM", "", "", "", "", ""],
            ["2:30 PM - 2:45 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["2:45 PM - 3:30 PM", "", "", "", "", ""],
            ["3:30 PM - 4:15 PM", "", "", "", "", ""],
            ["4:15 PM - 4:30 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["4:30 PM - 5:15 PM", "", "", "", "", ""],
            ["5:15 PM - 6:00 PM", "", "", "", "", ""],
        ],


        "3-3": [
            ["7:00 AM - 7:45 AM", "ZAMORA VENTURA, MARTA CONSUELO MOD 3.1 ST", "VENTURA SANTOS, SALOME DANILO MOD 3.4 ST", "POLIO CORTEZ, GERBER ALEXANDER\nMOD 3.6 ST", "ZAMORA VENTURA, MARTA CONSUELO MOD 3.1 ST", "ACEVEDO BENÍTEZ, CLAUDIA MAGDALENA MOD 3.2 ST"],
            ["7:45 AM - 8:30 AM", "ZAMORA VENTURA, MARTA CONSUELO MOD 3.1 ST", "VENTURA SANTOS, SALOME DANILO MOD 3.4 ST", "POLIO CORTEZ, GERBER ALEXANDER\nMOD 3.6 ST", "ZAMORA VENTURA, MARTA CONSUELO MOD 3.1 ST", "ACEVEDO BENÍTEZ, CLAUDIA MAGDALENA MOD 3.2 ST"],
            ["8:30 AM - 8:45 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["8:45 AM - 9:30 AM", "MARTÍNEZ DE ELÍAS, CLAUDIA RAQUEL MOD 3.8 ST", "VENTURA SANTOS, SALOME DANILO MOD 3.4 ST", "VENTURA SANTOS, SALOME DANILO\nMOD 3.3 ST", "MARTÍNEZ DE ELÍAS, CLAUDIA RAQUEL MOD 3.7 ST", "ZAMORA VENTURA, MARTA CONSUELO MOD 3.1 ST"],
            ["9:30 AM - 10:15 AM", "MARTÍNEZ DE ELÍAS, CLAUDIA RAQUEL MOD 3.8 ST", "VENTURA SANTOS, SALOME DANILO MOD 3.4 ST", "ZAMORA VENTURA, MARTA CONSUELO\nMOD 3.5 ST", "MARTÍNEZ DE ELÍAS, CLAUDIA RAQUEL MOD 3.7 ST", "ZAMORA VENTURA, MARTA CONSUELO MOD 3.1 ST"],
            ["10:15 AM - 10:30 AM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["10:30 AM - 11:15 AM", "VENTURA SANTOS, SALOME DANILO MOD 3.3 ST", "ACEVEDO BENÍTEZ, CLAUDIA MAGDALENA MOD 3.2 ST", "ZAMORA VENTURA, MARTA CONSUELO\nMOD 3.5 ST", "VENTURA SANTOS, SALOME DANILO MOD 3.3 ST", "MARTÍNEZ DE ELÍAS, CLAUDIA RAQUEL MOD 3.8 ST"],
            ["11:15 AM - 12:00 PM", "VENTURA SANTOS, SALOME DANILO MOD 3.3 ST", "ACEVEDO BENÍTEZ, CLAUDIA MAGDALENA MOD 3.2 ST", "ZAMORA VENTURA, MARTA CONSUELO\nMOD 3.5 ST", "VENTURA SANTOS, SALOME DANILO MOD 3.3 ST", "MARTÍNEZ DE ELÍAS, CLAUDIA RAQUEL MOD 3.8 ST"],
            ["12:00 PM - 1:00 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["1:00 PM - 1:45 PM", "", "", "", "", ""],
            ["1:45 PM - 2:30 PM", "", "", "", "", ""],
            ["2:30 PM - 2:45 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["2:45 PM - 3:30 PM", "", "", "", "", ""],
            ["3:30 PM - 4:15 PM", "", "", "", "", ""],
            ["4:15 PM - 4:30 PM", "RECESO", "RECESO", "RECESO", "RECESO", "RECESO"],
            ["4:30 PM - 5:15 PM", "", "", "", "", ""],
            ["5:15 PM - 6:00 PM", "", "", "", "", ""],
        ],

    },
};

let añoActual = "primero";
let seccionActual = "1-1";

document.addEventListener('DOMContentLoaded', () => {
    cargarHorario(añoActual, seccionActual);
    configurarBotones();
});

function configurarBotones() {
    const botonesAño = document.querySelectorAll('.btn-year');
    botonesAño.forEach(boton => {
        boton.addEventListener('click', function () {
            botonesAño.forEach(btn => btn.classList.remove('active'));
            this.classList.add('active');

            añoActual = this.getAttribute('data-year');

            document.querySelectorAll('.secciones').forEach(seccion => {
                seccion.style.display = 'none';
            });

            document.querySelector(`.secciones.${añoActual}`).style.display = 'flex';

            const primeraSeccion = document.querySelector(`.secciones.${añoActual} .btn-section`).getAttribute('data-section');
            seccionActual = primeraSeccion;

            document.querySelectorAll('.btn-section').forEach(boton => {
                boton.classList.remove('active');
            });
            document.querySelector(`.btn-section[data-section="${primeraSeccion}"]`).classList.add('active');

            cargarHorario(añoActual, seccionActual);
            actualizarTitulo();
        });
    });

    const botonesSeccion = document.querySelectorAll('.btn-section');
    botonesSeccion.forEach(boton => {
        boton.addEventListener('click', function () {
            botonesSeccion.forEach(btn => btn.classList.remove('active'));
            this.classList.add('active');

            seccionActual = this.getAttribute('data-section');
            cargarHorario(añoActual, seccionActual);
            actualizarTitulo();
        });
    });
}

function cargarHorario(año, seccion) {
    const tbody = document.querySelector('.tabla-horario tbody');
    tbody.innerHTML = '';

    const horarioSeccion = horarios[año][seccion];

    if (horarioSeccion && horarioSeccion.length > 0) {
        horarioSeccion.forEach(fila => {
            const tr = document.createElement('tr');

            fila.forEach(celda => {
                const td = document.createElement('td');
                td.textContent = celda;
                tr.appendChild(td);
            });

            tbody.appendChild(tr);
        });
    } else {
        const tr = document.createElement('tr');
        const td = document.createElement('td');
        td.colSpan = 6;
        td.textContent = 'Horario no disponible para esta sección';
        td.style.textAlign = 'center';
        td.style.padding = '20px';
        tr.appendChild(td);
        tbody.appendChild(tr);
    }
}

function actualizarTitulo() {
    const titulo = document.getElementById('titulo-seccion');
    const añoTexto = añoActual === 'primero'
        ? 'Primer Año'
        : añoActual === 'segundo'
            ? 'Segundo Año'
            : 'Tercer Año';

    titulo.textContent = `${añoTexto} - Sección ${seccionActual}`;
}
